// src/data.js
export const ALL_WORDS = [
  { eng: "provide", kor: "[동] 제공하다, 공급하다, 준비하다" },
  { eng: "develop", kor: "[동] 개발하다, 발달하다, 발전시키다" },
  { eng: "service", kor: "[명] 서비스, 근무, 봉사, 공공 업무" },
  { eng: "inform", kor: "[동] 알리다, 통지하다" },
  { eng: "relationship", kor: "[명] 관계" },
  { eng: "improve", kor: "[동] 향상시키다, 나아지다, 향상하다" },
  { eng: "individual", kor: "[형] 개인의, 개인적인[명] 개인" },
  { eng: "require", kor: "[동] 요구하다, 필요로 하다" },
  { eng: "advise", kor: "[동] 충고하다, 조언하다" },
  { eng: "social", kor: "[형] 사회의, 사교적인" },
  { eng: "amount", kor: "[명] 총액, 총계, 양[동] 총계가 ~이 되다" },
  { eng: "behave", kor: "[동] 행동하다" },
  { eng: "employ", kor: "[동] 고용하다, 쓰다" },
  { eng: "attitude", kor: "[명] 태도, 입장" },
  { eng: "research", kor: "[명] 연구하다, 조사하다[명] 연구, 조사" },
  { eng: "audience", kor: "[명] 청중, 관객" },
  {
    eng: "volunteer",
    kor: "[명] 지원자, 자원봉사, 자원봉사자[동] 지원하다, 자원봉사하다",
  },
  {
    eng: "influence",
    kor: "[명] 영향, 영향을 미치는 것[사람][동] 영향을 미치다",
  },
  { eng: "terrible", kor: "[형] 끔직한, 형편없는, 무서운" },
  { eng: "opportunity", kor: "[명] 기회" },
  { eng: "ability", kor: "[명] 능력, 재능" },
  { eng: "expense", kor: "[명] 비용, 지출" },
  { eng: "local", kor: "[형] 지역의, 장소의, 지방의" },
  { eng: "involve", kor: "[동] 관련시키다, 포함하다, 관련되다" },
  { eng: "stress", kor: "[명] 스트레스, 긴장, 강조[동] 강조하다, 압력을 주다" },
  { eng: "therefore", kor: "[부] 그러므로, 그 결과" },
  { eng: "positive", kor: "[형] 긍정적인, 낙관적인, 확신하는" },
  {
    eng: "average",
    kor: "[형] 평균의, 보통의[명] 평균, 보통 수준[동] 평균 ~이다",
  },
  { eng: "ride", kor: "[동] 타다[명] 타기, 태우기, 타고가기" },
  { eng: "encourage", kor: "[동] 격려하다, 권장하다, 부추기다, 촉구하다" },
  { eng: "determine", kor: "[동] 결정하다, 결심하다" },
  { eng: "international", kor: "[형] 국제의, 국제적인" },
  { eng: "consume", kor: "[동] 소비하다, 먹다[마시다]" },
  { eng: "impress", kor: "[동] 감동시키다, 깊은 인상을 주다" },
  { eng: "object", kor: "[명] 물건, 물체, 목표[동] 반대하다" },
  { eng: "available", kor: "[형] 이용할 수 있는, 쓸모있는, 시간이 있는" },
  { eng: "contain", kor: "[동] 들어있다, 포함하다, 함유하다, 억제하다" },
  { eng: "recognize", kor: "[동] 인지하다 , 인정하다, 알아보다" },
  { eng: "material", kor: "[명] 재료, 소재, 물질[형] 물질의" },
  {
    eng: "comfort",
    kor: "[명] 편안, 평안함, 위안, 위로[동] 편안하게 하다, 위로하다",
  },
  { eng: "emotion", kor: "[명] 감정" },
  { eng: "amaze", kor: "[동] 놀라게 하다" },
  { eng: "reduce", kor: "[동] 줄이다, 낮추다" },
  { eng: "discover", kor: "[동] 발견하다, 알아내다" },
  { eng: "decide", kor: "[동] 결정하다, 결심하다" },
  { eng: "benefit", kor: "[명] 이익, 혜택[동] 도움이 되다" },
  { eng: "affect", kor: "[동] 영향을 미치다" },
  { eng: "level", kor: "[명] 수준, 정도, 수평[형] 수평의" },
  { eng: "chemistry", kor: "[명] 화학" },
  { eng: "immediate", kor: "[형] 즉각적인, 시급한, 직접적인" },
  { eng: "thus", kor: "[부] 그러므로, 따라서" },
  { eng: "proper", kor: "[형] 적절한, 알맞은" },
  { eng: "performance", kor: "[명] 공연, 성과" },
  { eng: "essence", kor: "[명] 본질, 정수" },
  { eng: "economic", kor: "[형] 경제의, 경제학의" },
  { eng: "cell", kor: "[명] 세포" },
  { eng: "focus", kor: "[동] 집중하다[명] 초점" },
  { eng: "issue", kor: "[명] 논란거리, 쟁점, 문제" },
  { eng: "participate", kor: "[동] 참여하다, 참가하다(in)" },
  { eng: "demand", kor: "[명] 요구, 수요[동] 요구하다" },
  { eng: "occur", kor: "[동] 발생하다, 일어나다, (생각이) 떠오르다" },
  { eng: "complex", kor: "[형] 복잡한[명] 복잡체, 복합 건물" },
  { eng: "define", kor: "[동] 정의하다, 한계 짓다, 한정하다, 규정하다" },
  { eng: "proud", kor: "[형] 자랑스러워하는" },
  { eng: "aware", kor: "[형] 인지하는, 인식하고 있는, 알고 있는" },
  { eng: "contact", kor: "[동] 연락하다[명] 접촉, 연락" },
  { eng: "profession", kor: "[명] 직업, 직종, 전문직" },
  { eng: "detail", kor: "[명] 세부, 세부사항[동] 상술하다" },
  { eng: "approach", kor: "[동] 접근하다[명] 접근" },
  { eng: "career", kor: "[명] 직업, 경력" },
  { eng: "package", kor: "[명] 꾸러미, 포장, 포장된 짐[동] 포장하다" },
  { eng: "disappear", kor: "[동] 사라지다" },
  { eng: "novel", kor: "[명] 소설" },
  { eng: "secure", kor: "[형] 안전한, 안정된[동] 안전하게 하다" },
  { eng: "fashion", kor: "[명] 유행, 패션, 방식[동] 만들어 내다" },
  { eng: "despite", kor: "[전] ~에도 불구하고" },
  { eng: "background", kor: "[명] (그림, 사람, 사건)배경, 배경 지식" },
  { eng: "solution", kor: "[명] 해결, 해결책" },
  { eng: "generate", kor: "[동] 일으키다, 발생시키다" },
  { eng: "eventually", kor: "[부] 결국" },
  { eng: "decrease", kor: "[동] 줄다[감소하다], 줄이다[명] 감소" },
  { eng: "recycle", kor: "[동] 재활용하다" },
  { eng: "desire", kor: "[명] 욕구, 욕망[동] 바라다" },
  { eng: "balance", kor: "[명] 균형, 은행 잔고[동] 균형을 이루다" },
  { eng: "negative", kor: "[형] 부정적인" },
  { eng: "follow", kor: "[동] 따라가다,  (규칙을) 따르다" },
  { eng: "account", kor: "[명] 은행 계좌, 이야기, 설명[동] 설명하다" },
  { eng: "publish", kor: "[동] 발표하다, 출판하다" },
  { eng: "occasion", kor: "[명] 경우, 특별한 일" },
  { eng: "replace", kor: "[동] 대체하다" },
  { eng: "constant", kor: "[형] 일정한, 불변의[명] (수학에서의) 상수" },
  { eng: "expert", kor: "[명] 전문가" },
  { eng: "term", kor: "[명] 용어, 기간, 학기" },
  { eng: "relieve", kor: "[동] 경감하다, 안도시키다" },
  { eng: "describe", kor: "[동] 묘사하다, 표현하다" },
  { eng: "biology", kor: "[명] 생물학" },
  { eng: "due", kor: "[형] 만기의, ~하기로 되어 있는" },
  { eng: "equipment", kor: "[명] 장치, 장비" },
  { eng: "congratulate", kor: "[동] 축하하다" },
  { eng: "birth", kor: "[명] 탄생" },
  { eng: "compose", kor: "[동] 구성하다, 작곡하다, 작문하다" },
  { eng: "genius", kor: "[명] 천재, 천재성" },
  { eng: "reflect", kor: "[동] 반영하다, 반사하다, 숙고하다" },
  { eng: "cause", kor: "[동] ~의 원인이 되다, 야기하다[명] 원인" },
  { eng: "frequent", kor: "[형] 빈번한[동] (장소,모임에) 자주 가다" },
  { eng: "factor", kor: "[명] 요인, 요소" },
  { eng: "extreme", kor: "[형] 극단의[명] 극단" },
  { eng: "tend", kor: "[동] ~하는 경향이 있다, 돌보다" },
  { eng: "politics", kor: "[명] 정치, 정치학" },
  { eng: "insist", kor: "[동] 주장하다" },
  { eng: "extend", kor: "[동] 연장하다, 넓히다" },
  { eng: "lonely", kor: "[형] 외로운" },
  { eng: "habitat", kor: "[명] 서식지, 주거지" },
  { eng: "mental", kor: "[형] 정신의" },
  { eng: "steady", kor: "[형] 안정된, 한결같은, 꾸준한" },
  { eng: "exchange", kor: "[동] 교환하다" },
  { eng: "active", kor: "[형]  활동적인, 적극적인" },
  { eng: "species", kor: "[명] (생물분류상의) 종" },
  { eng: "athletic", kor: "[형] 운동의, 운동경기의" },
  { eng: "dental", kor: "[형] 치아의" },
  { eng: "delight", kor: "[명] 기쁨[동] 기쁘게 하다" },
  { eng: "confident", kor: "[형] 자신 있는" },
  { eng: "gradually", kor: "[부] 점차, 서서히" },
  { eng: "shadow", kor: "[명] 그림자[동] 그늘지게 하다" },
  { eng: "access", kor: "[명] 접근, 이용[동] 접근하다" },
  { eng: "announce", kor: "[동] 발표하다, 알리다" },
  { eng: "allow", kor: "[동] 허락하다, 인정하다" },
  { eng: "firm", kor: "[형] 확고한, 단단한[명] 회사" },
  { eng: "vary", kor: "[동] 바꾸다, 변하다, 다르다" },
  { eng: "injure", kor: "[동] 상처를 입히다, 손상시키다" },
  { eng: "permit", kor: "[동] 허용[허락]하다" },
  { eng: "response", kor: "[명] 응답, 반응" },
  { eng: "threat", kor: "[동] 위협, 협박" },
  { eng: "electricity", kor: "[명] 전기" },
  { eng: "disabled", kor: "[형] 장애를 가진, 무능력하게 된" },
  { eng: "lack", kor: "[명] 부족[동] ~이 부족하다" },
  { eng: "signify", kor: "[동] 의미하다, 중요하다" },
  { eng: "concentrate", kor: "[동] 집중하다" },
  { eng: "emphasize", kor: "[동] 강조하다" },
  { eng: "astronomy", kor: "[명] 천문학" },
  { eng: "flood", kor: "[명] 홍수[동] 범람시키다" },
  { eng: "fuel", kor: "[명] 연료[동] 연료를 가하다" },
  { eng: "manufacture", kor: "[동] 제조하다[명] 제조(업), 제품" },
  { eng: "movement", kor: "[명] 움직임, 운동" },
  { eng: "capable", kor: "[형] ~을 할 수 있는, 유능한" },
  { eng: "combine", kor: "[동] 결합하다, 겸비하다" },
  { eng: "gene", kor: "[명] 유전자" },
  { eng: "increase", kor: "[동] (수량이) 증가하다[명] 증가, 이자" },
  { eng: "victim", kor: "[명] 희생, 피해자" },
  { eng: "pressure", kor: "[명] 압력, 압박[동] 압력을 가하다" },
  { eng: "accompany", kor: "[동] 동반[동행]하다, 수반하다" },
  { eng: "frustrate", kor: "[동] 좌절시키다" },
  { eng: "construct", kor: "[동] 건설하다" },
  { eng: "dwindle", kor: "[동] 점점 줄어들다, 저하되다" },
  { eng: "commerce", kor: "[명] 상업, 교역" },
  { eng: "entertain", kor: "[동] 즐겁게 하다" },
  { eng: "predict", kor: "[동] 예언하다, 예측하다" },
  { eng: "apologize", kor: "[동] 사과하다" },
  { eng: "sight", kor: "[명] 시야, 광경, 시력" },
  { eng: "quantity", kor: "[명] 양" },
  { eng: "conclude", kor: "[동] 결론짓다, 끝내다" },
  { eng: "donate", kor: "[동] 기부하다" },
  { eng: "personality", kor: "[명] 개성, 성격, 특색" },
  { eng: "struggle", kor: "[동] 싸우다, 노력하다[명] 투쟁, 노력" },
  { eng: "advantage", kor: "[명] 유리한 점, 이점" },
  { eng: "variety", kor: "[명] 다양, 다양성" },
  { eng: "enable", kor: "[동] 가능하게 하다" },
  { eng: "instruction", kor: "[명] 지시, 제품 사용 설명서, 가르침" },
  { eng: "assume", kor: "[동] 추정하다, (태도 등을) 취하다" },
  { eng: "attempt", kor: "[동] 시도하다[명] 시도" },
  { eng: "incredible", kor: "[형] 믿을 수 없는, (믿기 어려울 만큼) 굉장한" },
  {
    eng: "feature",
    kor: "[명] 특징, 특집 기사, 얼굴 생김새[동] ~을 특징으로 하다, 주연하다",
  },
  { eng: "confuse", kor: "[동] 혼동하다, 혼란시키다" },
  { eng: "electronic", kor: "[형] 전자의" },
  { eng: "absorb", kor: "[동] 흡수하다, (사람, 마음을) 열중시키다" },
  { eng: "indicate", kor: "[동] 가리키다, 나타내다" },
  { eng: "analyze", kor: "[동] 분석하다" },
  {
    eng: "stock",
    kor: "[명] 재고품, 저장, 가축[동] 저장하다, (물품을) 들여놓다",
  },
  { eng: "resident", kor: "[명] 거주자" },
  { eng: "labor", kor: "[명] 노동, 산고[동] 노동하다" },
  { eng: "remark", kor: "[명] 의견, 주목[동] 의견을 말하다, ~에 주목하다" },
  { eng: "moral", kor: "[형] 도덕적인" },
  { eng: "embarrassed", kor: "[형] 당황한" },
  { eng: "claim", kor: "[동] 주장하다[명] 요구, 주장" },
  { eng: "reasonable", kor: "[형] 논리적인, 분별력 있는" },
  { eng: "interrupt", kor: "[동] 방해하다, 중단하다" },
  { eng: "discount", kor: "[명] 할인[동] 할인하다" },
  { eng: "creature", kor: "[명] 생물, 피조물" },
  { eng: "heal", kor: "[동] 치료하다, 낫게 하다" },
  { eng: "establish", kor: "[동] 설립하다, 확립하다, 제정하다" },
  { eng: "revolution", kor: "[명] 혁명, 갑작스러운 변화, 회전" },
  { eng: "criticize", kor: "[동] 비난하다" },
  { eng: "convince", kor: "[동] 확신시키다, 납득시키다" },
  { eng: "efficient", kor: "[형] 효율적인, 유능한" },
  { eng: "stranger", kor: "[명] 낯선 사람, 문외한" },
  { eng: "tide", kor: "[명] 조수, 흐름" },
  { eng: "obtain", kor: "[동] 획득하다, 통용되다, 행해지다" },
  { eng: "assist", kor: "[동] 도움을 주다" },
  { eng: "disaster", kor: "[명] 재앙, 재난, 재해" },
  { eng: "terrific", kor: "[형] 굉장한, 훌륭한" },
  { eng: "specific", kor: "구체적인, 특정한" },
  { eng: "react", kor: "반응하다, 반작용하다" },
  { eng: "independent", kor: "독립적인" },
  { eng: "theory", kor: "이론" },
  { eng: "qualify", kor: "자격을 얻다" },
  { eng: "consider", kor: "숙고하다, 고려하다" },
  { eng: "recall", kor: "상기하다, 철회하다, 회수하다; 상기, 철회" },
  { eng: "risk", kor: "위험; 위험을 감수하다" },
  { eng: "treatment", kor: "취급, 대우, 치료(법)" },
  { eng: "engage", kor: "관여하다, 약속하다, 약혼하다" },
  { eng: "motivate", kor: "동기를 부여하다" },
  { eng: "clue", kor: "실마리, 단서" },
  { eng: "cancer", kor: "암, 악성 종양" },
  { eng: "elder", kor: "나이가 위인; 연장자" },
  { eng: "depress", kor: "우울하게 하다, 의기소침(낙담)하게 하다" },
  { eng: "fascinate", kor: "매료시키다, 마음을 빼앗다" },
  { eng: "violent", kor: "난폭한, 폭력적인" },
  { eng: "alarm", kor: "놀람, 경보" },
  { eng: "edge", kor: "가장자리, 날카로움, 우위" },
  { eng: "deserve", kor: "~을 받을 만하다(가치가 있다)" },
  { eng: "route", kor: "길, 통로, 항로" },
  { eng: "psychology", kor: "심리, 심리학" },
  { eng: "passion", kor: "열정" },
  { eng: "import", kor: "수입하다, 의미하다; 수입" },
  { eng: "purchase", kor: "구매하다; 구매" },
  { eng: "conscience", kor: "양심" },
  { eng: "pose", kor: "자세를 취하다, (문제를) 제기하다; 자세" },
  { eng: "length", kor: "길이" },
  { eng: "severe", kor: "심한, 엄격한" },
  { eng: "decade", kor: "10년, 10년간" },
  { eng: "occupy", kor: "(시간, 장소를) 차지하다, 전념하다" },
  { eng: "acquire", kor: "습득하다" },
  { eng: "interact", kor: "상호 작용하다" },
  { eng: "brief", kor: "간단한; 간단한 보고; 간단히 알리다" },
  { eng: "observe", kor: "관찰하다, ~을 보다, 준수하다" },
  { eng: "poetry", kor: "시, 운문" },
  { eng: "salary", kor: "급료, 봉급" },
  { eng: "grain", kor: "곡물, 낟알" },
  { eng: "meaningful", kor: "의미 있는, 의미심장한" },
  { eng: "weed", kor: "잡초; 잡초를 제거하다" },
  { eng: "survival", kor: "[명] 생존" },
  { eng: "comment", kor: "[명] 논평, 주석 [동] 논평하다" },
  { eng: "leap", kor: "[동] 뛰다, 도약하다 [명] 도약" },
  { eng: "survey", kor: "[동] 둘러보다, 조사하다 [명] 설문 조사" },
  { eng: "typical", kor: "[형] 전형적인, 대표적인" },
  { eng: "mere", kor: "[형] 단지 ~에 불과한" },
  { eng: "mechanic", kor: "[명] 기계공" },
  { eng: "mood", kor: "[명] 분위기, 기분" },
  { eng: "approve", kor: "[동] 승인하다, 찬성하다" },
  { eng: "rural", kor: "[형] 시골의" },
  { eng: "finance", kor: "[명] 재정, 자금 [동] 자금을 조달하다" },
  { eng: "seek", kor: "[동] 찾다, 추구하다" },
  { eng: "operation", kor: "[명] 작업, 운영, 수술" },
  { eng: "crime", kor: "[명] 범죄" },
  { eng: "awful", kor: "[형] 끔찍한, 지독한" },
  { eng: "series", kor: "[명] 연속, 시리즈물" },
  { eng: "exhausted", kor: "[형] 고갈된, 기진맥진한" },
  { eng: "absolute", kor: "[형] 완전한, 절대적인" },
  { eng: "surround", kor: "[동] 둘러싸다" },
  { eng: "display", kor: "[동] 전시하다, 나타내다 [명] 전시" },
  { eng: "policy", kor: "[명] 정책, 수단" },
  { eng: "mass", kor: "[명] 덩어리, 집단" },
  { eng: "committee", kor: "[명] 위원회" },
  { eng: "accurate", kor: "[형] 정확한" },
  { eng: "arrange", kor: "[동] 정리하다, 준비하다" },
  { eng: "facility", kor: "[명] 시설, 편의" },
  { eng: "consult", kor: "[동] 상담하다, 참고하다" },
  { eng: "refer", kor: "[동] 언급하다, 위탁하다" },
  { eng: "attach", kor: "[동] 붙이다, 첨부하다" },
  { eng: "recover", kor: "[동] 회복하다, 되찾다" },
  { eng: "reward", kor: "[명] 보상 [동] 보답하다" },
  { eng: "enormous", kor: "[형] 엄청난, 거대한" },
  { eng: "domestic", kor: "[형] 국내의, 가정의" },
  { eng: "wealth", kor: "[명] 부, 재산" },
  { eng: "elementary", kor: "[형] 초보의, 기초적인" },
  { eng: "gap", kor: "[명] 격차, 틈" },
  { eng: "except", kor: "[전] ~을 제외하고 [동] 제외하다" },
  { eng: "journey", kor: "[명] 여행" },
  { eng: "plain", kor: "[형] 평범한, 명백한" },
  { eng: "downtown", kor: "[명] 도심 [형]도심의 [부] 도심지에서" },
  { eng: "previous", kor: "[형] 이전의, 앞의" },
  { eng: "produce", kor: "[동] 생산하다, 제조하다" },
  { eng: "remain", kor: "[동] 여전히 ~이다, 남다" },
  { eng: "break", kor: "[동] 깨다, 고장내다" },
  { eng: "slight", kor: "[형] 약간의, 경미한" },
  { eng: "include", kor: "[동] 포함하다" },
  { eng: "delay", kor: "[동] 연기하다, 미루다[명] 지연" },
  { eng: "file", kor: "[명] 서류철[동] 파일에 철하다, 제기하다" },
  { eng: "ethic", kor: "[명] 윤리" },
  { eng: "instant", kor: "[형] 즉각의, 즉석의[명] 순간" },
  { eng: "reveal", kor: "[동] 폭로하다, 드러내다" },
  { eng: "breed", kor: "[동] 낳다, 양육하다" },
  { eng: "leisure", kor: "[명] 여가[형] 한가한" },
  { eng: "urban", kor: "[형] 도시의" },
  { eng: "witness", kor: "[명] 목격자[동] 목격하다" },
  { eng: "admit", kor: "[동] 인정하다, 입학을 허가하다" },
  { eng: "muscle", kor: "[명] 근육, 힘" },
  { eng: "device", kor: "[명] 장치, 고안, 방책" },
  { eng: "suppose", kor: "[동] 추측하다, 가정하다" },
  { eng: "owe", kor: "[동] 빚지고 있다" },
  { eng: "intend", kor: "[동] ~할 작정이다, 의도하다" },
  { eng: "aspect", kor: "[명] 면, 관점" },
  { eng: "potential", kor: "[형] 잠재적인[명] 잠재력" },
  { eng: "award", kor: "[명] 상[동] (상 등을) 수여하다" },
  { eng: "preserve", kor: "[동] 보존하다, 보호하다" },
  { eng: "spot", kor: "[명] 장소, 점[동] 발견하다" },
  { eng: "underground", kor: "[형] 지하의, 비밀의[명] 지하" },
  { eng: "consequence", kor: "[명] 결과, 중요성" },
  { eng: "target", kor: "[명] 목표[동] 목표로 삼다" },
  { eng: "unless", kor: "[접] 만약 ~이 아니면" },
  { eng: "accomplish", kor: "[동] 이루다, 성취하다" },
  { eng: "adopt", kor: "[동] 입양하다, 채택하다" },
  { eng: "unique", kor: "[형] 독특한, 유일한" },
  { eng: "slip", kor: "[동] 미끄러지다, 실수하다[명] 종이 조각" },
  { eng: "civilization", kor: "[명] 문명" },
  { eng: "row", kor: "[명] 열, 줄[동] 배를 젓다" },
  { eng: "horizon", kor: "[명] 지평선" },
  { eng: "atmosphere", kor: "[명] 대기, 분위기" },
  { eng: "label", kor: "[명] 꼬리표, 상표[동] 라벨을 붙이다" },
  { eng: "decorate", kor: "[동] 장식하다, ~에게 훈장을 주다" },
  { eng: "identify", kor: "[동] ~임을 확인하다, 식별하다, 동일시하다" },
  { eng: "standard", kor: "[명] 표준, 기준 [형] 기준의, 표준의" },
  { eng: "scale", kor: "[명] 규모, 저울, 비늘" },
  { eng: "evident", kor: "[형] 명백한" },
  { eng: "seldom", kor: "[부] 거의 ~않는" },
  { eng: "secretary", kor: "[명] 비서, 장관" },
  { eng: "basis", kor: "[명] 원리, 기초" },
  { eng: "automatic", kor: "[형] 자동적인, 기계적인" },
  { eng: "region", kor: "[명] 지역" },
  { eng: "rise", kor: "[동] 일어나다, 오르다 [명] 상승" },
  { eng: "addict", kor: "[동] 중독시키다 [명] 중독자" },
  { eng: "disappoint", kor: "[동] 실망시키다" },
  { eng: "artificial", kor: "[형] 인공적인, 인조의" },
  { eng: "possess", kor: "[동] 소유하다, ~의 마음을 사로잡다" },
  { eng: "substance", kor: "[명] 물질, 본질, 실체" },
  { eng: "realistic", kor: "[형] 현실적인, 현실주의의" },
  { eng: "encounter", kor: "[동] (우연히) 만나다 [명] 마주침" },
  { eng: "differ", kor: "[동] 다르다, 의견을 달리하다" },
  { eng: "principle", kor: "[명] 원칙, 원리" },
  { eng: "memorize", kor: "[동] 기억하다" },
  { eng: "physics", kor: "[명] 물리학" },
  { eng: "evaluate", kor: "[동] 평가하다" },
  { eng: "tremendous", kor: "[형] 굉장한, 무시무시한" },
  { eng: "application", kor: "[명] 적용, 신청" },
  { eng: "vote", kor: "[명] 투표 [동] 투표하다" },
  { eng: "spread", kor: "[명] 퍼짐, 확산 [동] 펼치다, 퍼지다" },
  { eng: "impact", kor: "[명] 충격, 영향 [동] 충격을 주다" },
  { eng: "cooperate", kor: "[동] 협력하다" },
  { eng: "emit", kor: "[동] (빛, 열, 소리 등을)방출하다" },
  { eng: "request", kor: "[명] 요청 [동] 요청하다" },
  { eng: "guarantee", kor: "[동] 보장하다 [명] 보증" },
  { eng: "resist", kor: "[동] 저항하다" },
  { eng: "fulfill", kor: "[동] 달성하다, 이행하다" },
  { eng: "stink", kor: "[동] 역겹다, 악취를 풍기다" },
  { eng: "grant", kor: "[동] 수여하다, 승인하다" },
  { eng: "rely", kor: "[동] 의지하다, 믿다" },
  { eng: "permanent", kor: "[형] 영원한, 영구적인" },
  { eng: "emergency", kor: "[명] 비상 사태" },
  { eng: "rid", kor: "[동] 제거하다" },
  { eng: "theme", kor: "[명] 주제, 화제" },
  { eng: "hesitate", kor: "[동] 주저하다, 망설이다" },
  { eng: "location", kor: "[명] 위치, 장소" },
  { eng: "restrict", kor: "[동] 제한하다, 한정하다" },
  { eng: "organism", kor: "[명] 유기체, 생물" },
  { eng: "resolve", kor: "[동] 해결하다, 결심하다" },
  { eng: "offer", kor: "[동] 제공하다, 제안하다" },
  { eng: "distribute", kor: "[동] 분배하다, 분포시키다" },
  { eng: "rainforest", kor: "[명] 열대우림" },
  { eng: "circumstance", kor: "[명] 상황, 환경" },
  { eng: "interpret", kor: "[동] 해석하다, 통역하다" },
  { eng: "suitable", kor: "[형] 적절한, 적합한" },
  { eng: "curve", kor: "[명] 곡선, 속임수" },
  { eng: "annoy", kor: "[동] 괴롭히다, 귀찮게 하다" },
  { eng: "frighten", kor: "[동] 겁먹게 하다" },
  { eng: "estimate", kor: "[동] 평가하다[명] 견적, 평가" },
  { eng: "refuse", kor: "[동] 거절하다" },
  { eng: "adventure", kor: "[명] 모험[동] 위험에 빠뜨리다" },
  { eng: "entrance", kor: "[명] 입구, 입장" },
  { eng: "persuade", kor: "[동] 설득하다" },
  { eng: "perceive", kor: "[동] 인지하다, 인식하다" },
  { eng: "recite", kor: "[동] 암송하다" },
  { eng: "gather", kor: "[동] 모으다" },
  { eng: "cabin", kor: "[명] 객실, 선실, 오두막집" },
  { eng: "gear", kor: "[명] 장비,  기어[동] 맞게 조정하다" },
  { eng: "ray", kor: "[명] 광선" },
  { eng: "release", kor: "[동] 놓아주다, 방출하다[명] 석방, 발표" },
  { eng: "rank", kor: "[명] 지위, 계급[동] 매기다, (등급을)차지하다" },
  { eng: "symphony", kor: "[명] 교향곡" },
  { eng: "envy", kor: "[동] 부러워하다[명] 부러움" },
  { eng: "corporate", kor: "[형] 회사의, 법인의" },
  { eng: "alternative", kor: "[명] 대안[형] 대안의" },
  { eng: "retire", kor: "[동] 은퇴하다" },
  { eng: "appeal", kor: "[동] 호소하다, 관심을 끌다[명] 호소, 항의" },
  { eng: "identical", kor: "[형] 동일한, 일란성의" },
  { eng: "investment", kor: "[명] 투자" },
  { eng: "autograph", kor: "[명] 서명[동] 서명하다" },
  { eng: "slave", kor: "[명] 노예" },
  { eng: "harm", kor: "[명] 손해, 손상[동] 해치다" },
  { eng: "authority", kor: "[명] 권위, 당국" },
  { eng: "innocence", kor: "[명] 결백, 무죄, 순진" },
  { eng: "infant", kor: "[명] 유아, 유치원생" },
  { eng: "calculate", kor: "[동] 계산하다" },
  { eng: "charity", kor: "[명] 자선 단체" },
  { eng: "receive", kor: "[동] 받다" },
  { eng: "whereas", kor: "[접] 그런데, ~에 반해서" },
  { eng: "board", kor: "[명] 판자, 게시판[동] 타다" },
  { eng: "ignorant", kor: "[형] 무지한, 무식한" },
  { eng: "depend", kor: "[동] 의존하다, ~에 달려 있다" },
  { eng: "pure", kor: "[형] 순수한, 깨끗한" },
  { eng: "extinct", kor: "[형] 멸종된, 사라진" },
  { eng: "household", kor: "[명] 가정[형] 가정의" },
  { eng: "chapter", kor: "[명] (책의) 장, 시기, 사제단" },
  { eng: "refund", kor: "[동] 환불하다[명] 환불금" },
  { eng: "institute", kor: "[명] 기관, 협회" },
  { eng: "lately", kor: "[부] 최근에" },
  { eng: "accept", kor: "[동] 받아들이다" },
  { eng: "ashamed", kor: "[형] 부끄러워하는" },
  { eng: "dense", kor: "[형] 밀집한, (앞이 안 보이게) 짙은" },
  { eng: "rescue", kor: "[동] 구출하다[명] 구출" },
  { eng: "continue", kor: "[동] 계속하다" },
  { eng: "destination", kor: "[명] 목적지" },
  { eng: "expand", kor: "[동] 확장되다, 확장시키다" },
  { eng: "evolution", kor: "[명] 진화, 발전" },
  { eng: "hire", kor: "[동] 고용하다" },
  { eng: "isolate", kor: "[동] 고립시키다, 격리시키다" },
  { eng: "gravity", kor: "[명] 중력" },
  { eng: "genuine", kor: "[형] 진짜의, 진실된" },
  { eng: "statue", kor: "[명] 조각상" },
  { eng: "compete", kor: "[동] 경쟁하다" },
  { eng: "military", kor: "[형] 군의, 군사의[명] 군, 군대" },
  { eng: "logic", kor: "[명] 논리, 논리학" },
  { eng: "commit", kor: "[동] (죄 등을) 저지르다, 약속하다, 헌신하다" },
  { eng: "sensible", kor: "[형] 합리적인, 현명한" },
  { eng: "sum", kor: "[명] 금액, 합계" },
  { eng: "conserve", kor: "[동] 보존하다, 보호하다" },
  { eng: "swing", kor: "[동] 흔들다, 휘두르다" },
  { eng: "marriage", kor: "[명] 결혼, 결혼 생활" },
  { eng: "reproduce", kor: "[동] 번식하다, 재생하다, 복제하다" },
  { eng: "tone", kor: "[명] 음조, 어조, 억양 [동] 조화하다, 탄력있게 만들다" },
  { eng: "concept", kor: "[명] 개념" },
  { eng: "invitation", kor: "[명] 초대" },
  { eng: "precise", kor: "[형] 정확한, 정밀한" },
  { eng: "formal", kor: "[형] 공식적인, 격식을 차린" },
  { eng: "particle", kor: "[명] 작은 조각, 입자" },
  { eng: "cancel", kor: "[동] 취소하다" },
  { eng: "return", kor: "[동] 돌아가다, 돌려주다[명] 돌아감, 귀향" },
  { eng: "departure", kor: "[명] 출발, 떠남, 일탈" },
  { eng: "apparent", kor: "[형] 명백한" },
  { eng: "visual", kor: "[형] 눈에 보이는, 시각의" },
  { eng: "agriculture", kor: "[명] 농업" },
  { eng: "rite", kor: "[명] 의식, 의례" },
  { eng: "poverty", kor: "[명] 가난" },
  { eng: "sculpture", kor: "[명] 조각상" },
  { eng: "descend", kor: "[동] 내려가다, 내려오다" },
  { eng: "leak", kor: "[동] 새다[명] 새는 구멍" },
  { eng: "portion", kor: "[명] 부분, 1인분" },
  { eng: "companion", kor: "[명] 친구, 동료" },
  { eng: "diligent", kor: "[형]근면한" },
  { eng: "distinct", kor: "[형] 뚜렷한, 다른" },
  { eng: "component", kor: "[명] 구성 요소[형] 구성하는" },
  { eng: "current", kor: "[형] 현재의, 지금의" },
  { eng: "universal", kor: "[형] 보편적인, 전 세계의" },
  { eng: "trap", kor: "[명] 덫[동] 가두다" },
  { eng: "eager", kor: "[형] 갈망하는" },
  { eng: "legal", kor: "[형] 법률의, 합법적인" },
  { eng: "demonstrate", kor: "[동] 입증하다, 시위하다, 설명하다" },
  { eng: "democracy", kor: "[명] 민주주의" },
  { eng: "mature", kor: "[형] 성숙한[동] 성숙하다" },
  { eng: "brilliant", kor: "[형] 빛나는, 훌륭한" },
  { eng: "annual", kor: "[형] 연간의, 해마다의" },
  { eng: "faith", kor: "[명] 믿음, 신념" },
  {
    eng: "spare",
    kor: "[동] (시간, 돈을) 할애하다, (고생을) 면하게 하다[형] 여분의",
  },
  { eng: "transfer", kor: "[동] 이동하다, 옮기다, 환승하다[명] 이[동] 환승" },
  { eng: "refrigerator", kor: "[명] 냉장고" },
  { eng: "oppose", kor: "[동] 반대하다" },
  { eng: "desperate", kor: "[형] 절망적인, 필사적인" },
  { eng: "remote", kor: "[형] 멀리 떨어진, 원격 조정의" },
  { eng: "offend", kor: "[동] 불쾌하게 하다" },
  { eng: "awake", kor: "[형] 깨어있는" },
  { eng: "aim", kor: "[동] 목표로 하다, 겨누다[명] 목표" },
  { eng: "option", kor: "[명] 선택, 선택권" },
  { eng: "insight", kor: "[명] 통찰력" },
  { eng: "achieve", kor: "[동] 이루다, 성취하다" },
  { eng: "civil", kor: "[형] 시민의, 민간의" },
  { eng: "pause", kor: "[동] 잠시 멈추다[명] 중단" },
  { eng: "prove", kor: "[동] 입증하다" },
  { eng: "lecture", kor: "[명] 강의[동] 강의를 하다" },
  { eng: "minor", kor: "[형] 사소한, [명] 미성년자[동] 부전공하다" },
  { eng: "duty", kor: "[명] 의무, 관세" },
  { eng: "vigor", kor: "[명] 활력" },
  { eng: "organize", kor: "[동] 조직하다, 구성하다" },
  { eng: "chief", kor: "[명] 우두머리[형] 우두머리의, 주요한" },
  { eng: "complicated", kor: "[형] 복잡한" },
  { eng: "digest", kor: "[동] 소화하다[명] 요약" },
  { eng: "shortage", kor: "[명] 부족, 결함" },
  { eng: "laboratory", kor: "[명] 실험실[형] 실험의" },
  { eng: "arrive", kor: "[동] 도착하다" },
  { eng: "generous", kor: "[형] 관대한, 넉넉한" },
  { eng: "laundry", kor: "[명] 세탁물" },
  { eng: "transform", kor: "[동] 변형시키다, 변환하다" },
  { eng: "discipline", kor: "[명] 규율, 훈련[동] 훈육하다, 징계하다" },
  { eng: "forbid", kor: "[동] 금지하다" },
  { eng: "ultimate", kor: "[형] 궁극적인, 최후의" },
  { eng: "thrive", kor: "[동] 번영하다, 발전하다" },
  { eng: "conversation", kor: "[명] 대화, 회담" },
  { eng: "bet", kor: "[동] 돈을 걸다, 내기를 하다[명] 내기" },
  { eng: "royal", kor: "[형] 왕족의, 왕의" },
  { eng: "ruin", kor: "[동] 망치다, 파멸시키다[명] 파멸, 파산" },
  { eng: "worship", kor: "[동] 숭배하다, 예배하다[명] 숭배, 예배" },
  { eng: "evil", kor: "[형] 사악한[명] 악" },
  { eng: "scarce", kor: "[형] 부족한, 드문" },
  { eng: "afterward", kor: "[부] 나중에, 그 후에" },
  { eng: "client", kor: "[명] 고객, 의뢰인" },
  { eng: "insure", kor: "[동] 보험을 계약하다, 안전하게 하다" },
  { eng: "fancy", kor: "[명] 공상[형] 화려한[동] 공상하다" },
  { eng: "surgery", kor: "[명] 외과 수술" },
  { eng: "assign", kor: "[동] 할당하다, 지정하다" },
  { eng: "regulate", kor: "[동] 규제하다, 조절하다" },
  { eng: "shelf", kor: "[명] 선반" },
  { eng: "utility", kor: "[명] 공익사업, 유용성" },
  { eng: "necessity", kor: "[명] 필요, 필수, 필수품" },
  { eng: "yield", kor: "[동] 생산하다, 굴복하다, 양도하다[명] 수확(물)" },
  { eng: "decline", kor: "[명] 감소, 쇠퇴[동] 감소하다, 쇠퇴하다, 거절하다" },
  { eng: "coincidence", kor: "[명] 우연의 일치, 동시에 일어난 사건" },
  { eng: "aside", kor: "[부] 한쪽으로, 제쳐 두고" },
  { eng: "contemporary", kor: "[형] 현대의, 동시대의" },
  { eng: "bless", kor: "[동] 축복하다, 감사하다" },
  { eng: "explain", kor: "[동] 설명하다" },
  { eng: "prior", kor: "[형] 이전의, 우선하는" },
  { eng: "tolerate", kor: "[동] 참다, 용인하다" },
  { eng: "measure", kor: "[동] 측정하다[명] 측정, 수단" },
  { eng: "abstract", kor: "[형] 추상적인[명] 추상, 개요" },
  { eng: "cottage", kor: "[명] 오두막집" },
  { eng: "correct", kor: "[형] 올바른, 정확한[동] 바로잡다, 정정하다" },
  { eng: "confirm", kor: "[동] 확인하다, 입증하다, (결심을) 굳게 하다" },
  { eng: "imitate", kor: "[동] 모방하다" },
  { eng: "prey", kor: "[명] 먹이, 희생자" },
  { eng: "defeat", kor: "[동] 패배시키다[명] 패배" },
  { eng: "illustrate", kor: "[동] 설명하다, (분명히) 보여주다, 삽화를 넣다" },
  { eng: "fuse", kor: "[명] 퓨즈, 도화선[동] 융합하다" },
  { eng: "pupil", kor: "[명] 학생, 눈동자" },
  { eng: "intellect", kor: "[명] 지성" },
  { eng: "spice", kor: "[명] 향신료, 양념" },
  { eng: "tempt", kor: "[동] 유혹하다 (관심을) 끌다" },
  { eng: "inspire", kor: "[동] 영감을 주다, 고무시키다, 격려하다" },
  { eng: "dine", kor: "[동] 식사하다, 만찬을 대접하다" },
  { eng: "literally", kor: "[부] 문자 그대로" },
  { eng: "appropriate", kor: "[형] 적절한" },
  { eng: "resort", kor: "[명] 휴양지, 의지[동] 의지하다, 자주 가다" },
  { eng: "grab", kor: "[동] 움켜쥐다[명] 움켜쥠" },
  { eng: "propose", kor: "[동] 제안하다, 청혼하다" },
  { eng: "wreck", kor: "[명] 난파선, 사고[동] 난파시키다" },
  { eng: "document", kor: "[명] 문서, 서류[동] 기록하다" },
  { eng: "suspect", kor: "[동] 의심하다[명] 용의자" },
  { eng: "alien", kor: "[형] 외국의, 이질적인[명] 외국인, 외계인" },
  { eng: "prohibit", kor: "[동] 금지하다" },
  { eng: "install", kor: "[동] 설치하다" },
  { eng: "triumph", kor: "[명] 승리[동] 승리하다" },
  { eng: "scholarship", kor: "[명] 장학금, 학문" },
  { eng: "execute", kor: "[동] 실행하다, 처형하다" },
  { eng: "ensure", kor: "[동] 반드시 ~하게 하다, 보장하다, 확실하게 하다" },
  { eng: "receipt", kor: "[명] 영수증" },
  { eng: "defect", kor: "[명] 결점, 결함[동] (국가•당 등을) 버리다" },
  { eng: "trait", kor: "[명] 특징, 특성" },
  { eng: "modest", kor: "[형] 겸손한, 미천한, 알맞은" },
  { eng: "virtual", kor: "[형] 실제의, 가상의, 사실상의" },
  { eng: "compare", kor: "[동] 비교하다, 비유하다" },
  { eng: "address", kor: "[명] 주소, 연설, 인사말[동] 연설하다, 접근하다" },
  { eng: "inner", kor: "[형] 안쪽의, 내적인, 내부의" },
  { eng: "contrary", kor: "[형] 반대의, 불리한[명] 정반대, 반대의 것" },
  { eng: "split", kor: "[동] 나뉘다, 분열되다, 찢다, 쪼개다[명] 틈, 분열" },
  { eng: "supervise", kor: "[동] 감독하다, 관리하다, 통제하다" },
  { eng: "inhabit", kor: "[동] ~에 살다, 거주하다" },
  { eng: "appear", kor: "[동] 나타나다, ~인 것 같다" },
  { eng: "commute", kor: "[동] 통근하다[명] 통근(거리)" },
  { eng: "earthquake", kor: "[명] 지진, (사회•정치적) 대변동" },
  { eng: "enroll", kor: "[동] 등록하다, 입학하다" },
  { eng: "debate", kor: "[동] 논쟁하다, 토론하다[명] 논쟁, 토론" },
  { eng: "abandon", kor: "[동] 버리다, 포기하다" },
  { eng: "conquer", kor: "[동] 정복하다, 이기다, 극복하다" },
  { eng: "nevertheless", kor: "[부] 그럼에도 불구하고" },
  { eng: "seal", kor: "[동] 봉인하다[명] 봉인, 도장, 바다표범" },
  { eng: "greed", kor: "[명] 탐욕, 식탐" },
  { eng: "contract", kor: "[명] 계약, 계약서[동] 계약하다, 수축하다" },
  { eng: "nutrition", kor: "[명] 영양" },
  { eng: "retail", kor: "[명] 소매[동] 소매하다[부] 소매로" },
  { eng: "prejudice", kor: "[명] 편견, 선입관[동] 편견을 갖게 하다" },
  { eng: "register", kor: "[동] 등록하다, 기재하다[명] 등록부" },
  { eng: "agency", kor: "[명] 기관, 대행사, 대리점" },
  { eng: "nurture", kor: "[동] 양육하다, 양성하다, 교육하다[명] 교육, 양육" },
  { eng: "priest", kor: "[명] 성직자" },
  { eng: "elegant", kor: "[형] 우아한, 고상한" },
  { eng: "impose", kor: "[동] 부과하다, 강요하다" },
  { eng: "arise", kor: "[동] 발생하다, 일어나다, 생겨나다" },
  { eng: "modify", kor: "[동] 수정하다, 변형하다" },
  { eng: "masterpiece", kor: "[명] 대표작, 대작, 명작" },
  { eng: "harsh", kor: "[형] 가혹한, 거친" },
  { eng: "drought", kor: "[명] 가뭄" },
  { eng: "criteria", kor: "[형] 기준, 표준 (criterion의 복수형)" },
  { eng: "extraordinary", kor: "[형] 비범한, 기이한, 놀라운" },
  { eng: "dim", kor: "[형] 희미한, 어둑한 [동] 어둑하게 하다" },
  { eng: "general", kor: "[형] 일반적인, 전반적인 [명] 장군" },
  { eng: "scream", kor: "[동] 비명을 지르다 [명] 비명" },
  { eng: "spill", kor: "[동] 흘리다, 쏟다" },
  {
    eng: "glare",
    kor: "[동] 노려보다, 반짝 반짝 빛나다 [명] 노려봄, 눈부신 빛",
  },
  { eng: "swallow", kor: "[명] 삼킴, 제비 [동] 삼키다" },
  { eng: "usual", kor: "[형] 늘 하는, 흔히 있는" },
  { eng: "routine", kor: "[명] 틀에 박힌 일 [형] 일상적인, 지루한" },
  { eng: "eliminate", kor: "[동] 제거하다, 삭제하다" },
  { eng: "deny", kor: "[동] 부인하다, 거절하다" },
  { eng: "sensitive", kor: "[형] 민감한, 예민한" },
  { eng: "tragic", kor: "[형] 비극적인" },
  { eng: "deprive", kor: "[동] 빼앗다, 강탈하다" },
  { eng: "conscious", kor: "[형] 의식하는, 의식이 있는" },
  { eng: "interfere", kor: "[동] 간섭하다" },
  { eng: "temporary", kor: "[형] 임시의" },
  { eng: "council", kor: "[명] 의회" },
  { eng: "adolescent", kor: "[명] 청소년 [형] 청소년의" },
  { eng: "arctic", kor: "[형] 북극의" },
  { eng: "capture", kor: "[동] 붇잡다, 점유하다" },
  { eng: "dilute", kor: "[형] 묽은 [동] 묽게 하다, 약화시키다" },
  { eng: "associate", kor: "[동] 연상하다, 어울리다 [명] 동료" },
  { eng: "figure", kor: "[명] 숫자, 인물 [동] 이해하다, 계산하다" },
  { eng: "warehouse", kor: "[명] 창고" },
  { eng: "crew", kor: "[명] 승무원, (특별한 기술의)팀 [동] 승무원으로 일하다" },
  { eng: "barrier", kor: "[명] 장벽, 장애물" },
  { eng: "pedestrian", kor: "[명] 보행자 [형] 보행자의" },
  { eng: "glance", kor: "[동] 흘꿋 보다 [명] 흘끗 봄" },
  { eng: "errand", kor: "[명] 심부름" },
  { eng: "irritate", kor: "[동] 짜증나게 하다, 자극하다" },
  { eng: "welfare", kor: "[명] 복지, 행복" },
  { eng: "cruel", kor: "[형] 잔인한, 비참한" },
  { eng: "fold", kor: "[동] 주름 [동] 접다" },
  { eng: "trial", kor: "[명] 재판, 시험" },
  { eng: "tribe", kor: "[명] 부족" },
  { eng: "profound", kor: "[형] 깊은, 심오한" },
  { eng: "tradition", kor: "[명] 전통" },
  { eng: "distinguish", kor: "[동] 구별하다" },
  { eng: "statement", kor: "[명] 진술, 성명, 진술서" },
  { eng: "prevail", kor: "[동] 만연하다, 우세하다" },
  { eng: "widespread", kor: "[형] 널리 퍼진" },
  { eng: "result", kor: "[명] 결과" },
  { eng: "fade", kor: "[동] 사라지다, (색깔이) 바래다" },
  { eng: "progress", kor: "[명] 진전, 진보[동] 진보하다" },
  { eng: "weapon", kor: "[명] 무기" },
  { eng: "drastic", kor: "[형] 과감한, 격렬한" },
  { eng: "reinforcement", kor: "[명] 병력 증강, 강화" },
  { eng: "wonder", kor: "[동] 궁금해하다, 놀라다[명] 놀라움" },
  { eng: "pile", kor: "[명] 더미[동] 쌓다" },
  { eng: "protect", kor: "[동] 보호하다" },
  { eng: "infection", kor: "[명] 감염" },
  { eng: "stiffen", kor: "[동] 굳어지다" },
  { eng: "endanger", kor: "[동] 위험에 빠뜨리다" },
  { eng: "adjust", kor: "[동] 조절하다, 적응하다" },
  { eng: "peer", kor: "[명] 동료, 또래[동] 자세히 들여다보다" },
  { eng: "renew", kor: "[동] 새롭게 하다, 연장하다" },
  { eng: "germ", kor: "[명] 세균, 싹, 근원" },
  { eng: "atom", kor: "[명] 원자" },
  { eng: "realize", kor: "[동] 깨닫다, 실현하다" },
  { eng: "enrich", kor: "[동] 부유하게 하다" },
  { eng: "noble", kor: "[형] 고결한, 귀족의" },
  { eng: "repair", kor: "[동] 수리하다[명] 수리" },
  { eng: "candidate", kor: "[명] 후보자" },
  { eng: "ideal", kor: "[형] 이상적인[명] 이상" },
  { eng: "crop", kor: "[명] 농작물" },
  { eng: "ethnic", kor: "[형] 민족의" },
  { eng: "foretell", kor: "[동] 예언하다" },
  { eng: "wholesale", kor: "[형] 도매의, 대량의" },
  { eng: "debt", kor: "[명] 부채" },
  { eng: "representative", kor: "[명] 대표자" },
  { eng: "shift", kor: "[동] 바꾸다[명] 변화" },
  { eng: "strict", kor: "[형] 엄격한, 엄밀한" },
  { eng: "appliance", kor: "[명] 가전제품" },
  { eng: "furthermore", kor: "[부] 더욱이, 게다가" },
  { eng: "excess", kor: "[명] 초과, 과다" },
  { eng: "command", kor: "[동] 명령하다, 지휘하다[동] 명령, 지휘" },
  { eng: "ecosystem", kor: "[명] 생태계" },
  { eng: "fame", kor: "[명] 명성" },
  { eng: "oral", kor: "[형] 입의[명] 구술시험" },
  { eng: "drift", kor: "[명] 표류, 일반적인 경향[동] 떠돌다, 방황하다" },
  { eng: "outstanding", kor: "[형] 뛰어난, 눈에 띄는" },
  { eng: "mislead", kor: "[동] 잘못 판단하게 하다" },
  { eng: "dedicate", kor: "[동] (시간, 노력을) 바치다" },
  { eng: "avoid", kor: "[동] 피하다, 방지하다" },
  { eng: "initial", kor: "[형] 초기의, 처음의 [명] 머리글자 (이니셜)" },
  { eng: "sink", kor: "[동] 가라앉다" },
  { eng: "beard", kor: "[명] 턱수염" },
  { eng: "haste", kor: "[명] 서두름" },
  { eng: "crush", kor: "[동] 으스러뜨리다, 빻다" },
  { eng: "confront", kor: "[동] 맞서다, 직면하다" },
  { eng: "destiny", kor: "[명] 운명" },
  { eng: "hardship", kor: "[명] 고난, 고통" },
  { eng: "escape", kor: "[동] 탈출하다, 벗어나다 [명] 탈출, 도피" },
  { eng: "valid", kor: "[형] 타당한, 유효한" },
  { eng: "entire", kor: "[형] 전체의, 완전한 [명] 전부, 전체" },
  { eng: "dispose", kor: "[동] 배치하다, 처리하다" },
  { eng: "optimal", kor: "[형] 최적의" },
  { eng: "hydrogen", kor: "[명] 수소" },
  { eng: "thread", kor: "[명] 실 [동] 실을 꿰다" },
  { eng: "dynasty", kor: "[명] 왕조" },
  { eng: "scatter", kor: "[동] 뿌리다, 흩어지다" },
  { eng: "gamble", kor: "[동] 돈을 걸다, 도박을 하다 [명] 도박" },
  { eng: "temper", kor: "[명] 성질, 기분" },
  { eng: "exist", kor: "[동] 존재하다, 살아가다" },
  { eng: "undoubtedly", kor: "[부] 의심할 여지없이, 확실히" },
  { eng: "raft", kor: "[명] 뗏목, 비닐보트" },
  { eng: "minimal", kor: "[형] 최소의, 아주 적은" },
  { eng: "soak", kor: "[동] 흠뻑 적시다" },
  { eng: "craft", kor: "[명] 공예, 기술 [동] 공들여 만들다" },
  { eng: "combat", kor: "[명] 전투 [동] 싸우다" },
  { eng: "cease", kor: "[동] 중단하다" },
  { eng: "ceiling", kor: "[명] 천장, 최고 한도" },
  { eng: "unify", kor: "[동] 통합하다, 통일하다" },
  { eng: "perspective", kor: "[명] 견해, 관점" },
  { eng: "doom", kor: "[명] 나쁜 운명 [동] 운명 짓다" },
  { eng: "bump", kor: "[동] 부딫치다" },
  { eng: "primary", kor: "[형] 주된, 초기의" },
  { eng: "genre", kor: "[명] 형식, 장르" },
  { eng: "erase", kor: "[동] 지우다" },
  { eng: "review", kor: "[동] 복습하다, 재검토하다 [명] 복습, 검토, 비평" },
  { eng: "vital", kor: "[형] 필수적인, 중요한, 생명 유지와 관련된" },
  { eng: "incident", kor: "[명] 사건, 일어난 일[형] 일어나기 쉬운" },
  { eng: "session", kor: "[명] 시간, 회의, 기간, 학기" },
  { eng: "obvious", kor: "[형] 분명한, 명백한" },
  { eng: "moderate", kor: "[형] 온건한, 적당한" },
  { eng: "budget", kor: "[명] 예산, 예산안" },
  { eng: "graze", kor: "[동] 풀을 뜯다, 방목하다" },
  { eng: "fragile", kor: "[형] 부서지기 쉬운" },
  { eng: "myth", kor: "[명] 신화, 사회적 통념" },
  { eng: "fur", kor: "[명] 부드러운 털, 모피" },
  { eng: "indifferent", kor: "[형] 무관심한" },
  {
    eng: "strain",
    kor: "[명] 긴장, 압박[동] 잡아당기다, 긴장시키다, 혹사하다",
  },
  { eng: "ingredient", kor: "[명] 재료, 성분" },
  { eng: "dismiss", kor: "[동] 묵살하다, 해고하다, 해산시키다" },
  { eng: "geometry", kor: "[명] 기하학" },
  { eng: "glacier", kor: "[명] 빙하" },
  { eng: "urge", kor: "[동] 촉구하다, 강요하다" },
  { eng: "celebrity", kor: "[명] 유명 인사, 명성" },
  { eng: "antique", kor: "[형] 고대의, 옛날의, 고풍의[명] 골동품" },
  { eng: "profit", kor: "[명] 이익, 이윤[동] 이익을 얻다" },
  { eng: "sphere", kor: "[명] 구, 구체" },
  { eng: "inherit", kor: "[동] 상속받다, 물려받다" },
  { eng: "disgrace", kor: "[명] 불명예, 수치" },
  { eng: "crawl", kor: "[동] 기어가다, 서행하다[명] 기어가기, 서행" },
  { eng: "scratch", kor: "[동] 긁다, 할퀴다[명] 긁힌 자국, 찰과상" },
  { eng: "diabetes", kor: "[명] 당뇨병" },
  { eng: "congestion", kor: "[명] 혼잡, 밀집" },
  { eng: "constitute", kor: "[동] 구성하다, 설립하다, 제정하다" },
  { eng: "flow", kor: "[명] 흐름[동] 흐르다" },
  { eng: "investigate", kor: "[동] 조사하다, 수사하다" },
  { eng: "barter", kor: "[명] 물물 교환, 교역품[동] 물물 교환하다" },
  { eng: "circular", kor: "[형] 원의, 순환의" },
  { eng: "chilly", kor: "[형] 쌀쌀한, 냉담한" },
  { eng: "ancestor", kor: "[명] 조상, 선조" },
  { eng: "fierce", kor: "[형] 사나운, 맹렬한" },
  { eng: "vague", kor: "[형] 희미한, 막연한, 모호한" },
  { eng: "rough", kor: "[형] 거친, 난폭한, 대강의" },
  { eng: "content", kor: "[명] 내용, 목차[형] 만족하는" },
  { eng: "obstacle", kor: "[명] 장애물, 방해가 되는 것" },
  { eng: "editorial", kor: "[형] 편집자의[명] 사설, 논설" },
  { eng: "abolish", kor: "[동] 폐지하다" },
  { eng: "assure", kor: "[동] 확실하게 하다, 보증하다" },
  { eng: "form", kor: "[명] 형태, 종류[동] 형성하다" },
  { eng: "gender", kor: "[명] 성, 성별" },
  { eng: "innovation", kor: "[명] 혁신" },
  { eng: "opponent", kor: "[명] 상대, 반대자[형] 반대하는" },
  { eng: "present", kor: "[형] 현재의[명] 현재, 선물[동] 제출하다 나타내다" },
  { eng: "fertile", kor: "[형] 비옥한, 기름진" },
  { eng: "emperor", kor: "[명] 황제" },
  { eng: "dwell", kor: "[동] 거주하다, 살다" },
  { eng: "chore", kor: "[명] 허드렛일, 집안일" },
  { eng: "rehearsal", kor: "[명] 리허설, 예행연습" },
  { eng: "fossil", kor: "[명] 화석" },
  { eng: "glitter", kor: "동사 반짝이다명사 반짝임" },
  { eng: "carve", kor: "[동] 새기다, 조각하다" },
  { eng: "decay", kor: "[동] 부패하다, 쇠퇴하다[명] 부패, 쇠퇴" },
  { eng: "protein", kor: "[명] 단백질" },
  { eng: "backward", kor: "[부] 뒤쪽으로 후방에 거꾸로" },
  { eng: "translate", kor: "[동] 번역하다, 옮기다" },
  { eng: "refresh", kor: "[동] 상쾌하게 하다, 새롭게 하다" },
  { eng: "tissue", kor: "[명] (생물) 조직" },
  { eng: "lord", kor: "[명] 군주" },
  { eng: "substitute", kor: "[동] 대체하다[명] 대리자, 대체물" },
  { eng: "scan", kor: "[동] 정밀 검사하다, 유심히 쳐다보다" },
  { eng: "pottery", kor: "[명] 도자기, 도예" },
  { eng: "layer", kor: "[명] 층, 겹" },
  { eng: "property", kor: "[명] 재산, 소유물 , 부동산" },
  { eng: "justify", kor: "[동] 정당화하다" },
  { eng: "polish", kor: "[동] 닦다, 윤을 내다, (문장 등을)다듬다" },
  { eng: "flavor", kor: "[명] 맛동사 맛을 내다" },
  { eng: "imprint", kor: "[동] 찍다 감명시키다명사 찍은 자국, 인상" },
  { eng: "heritage", kor: "[명] 유산, 세습 재산" },
  { eng: "strive", kor: "[동] 노력하다, 애쓰다 , 투쟁하다" },
  { eng: "radiant", kor: "[형] 빛나는, 아주 밝은" },
  { eng: "exclaim", kor: "[동] (감탄하며)외치다" },
  { eng: "asset", kor: "[명] 자산, 재산" },
  { eng: "portray", kor: "[동] 묘사하다, 설명하다, 초상을 그리다" },
  { eng: "administer", kor: "[동] 관리•운영하다, 집행하다, 주다" },
  { eng: "wage", kor: "[명] 급료" },
  { eng: "subscribe", kor: "[동] 정기 구독하다" },
  { eng: "architecture", kor: "[명] 건축학, 건축 양식" },
  { eng: "territory", kor: "[명] 영토, 영역" },
  { eng: "strategy", kor: "[명] 전략, 계획" },
  { eng: "hence", kor: "[부] 그러므로, 향후" },
  { eng: "panic", kor: "[형] 당황한 [명] 공황" },
  { eng: "wilderness", kor: "[명] 황무지" },
  { eng: "attract", kor: "[동] 끌다, 매혹하다" },
  { eng: "category", kor: "[명] 부류, 종류" },
  { eng: "murder", kor: "[동] 죽이다 [명] 살인" },
  { eng: "funeral", kor: "[명] 장례식 [형] 장례의" },
  { eng: "humiliation", kor: "[명] 창피 줌, 굴욕" },
  { eng: "ban", kor: "[동] 금지하다 [명] 금지" },
  {
    eng: "flush",
    kor: "[동] 물로 씻어내리다, (얼굴이) 붉어지다 [명] 물로 씻어냄, 홍조",
  },
  { eng: "omit", kor: "[동] ~을 생략하다" },
  { eng: "outcome", kor: "[명] 결과" },
  { eng: "despair", kor: "[명] 절망 [동] 절망하다" },
  { eng: "alert", kor: "[형] 조심하는 [동] 경고하다 [명] 경계" },
  { eng: "compact", kor: "[형] 아담한, 빽빽한 [명] 계약, 협정" },
  { eng: "likewise", kor: "[부] 마찬가지로" },
  { eng: "astonish", kor: "[동] 깜짝 놀라게 하다" },
  { eng: "optimistic", kor: "[형] 낙천적인" },
  { eng: "loyal", kor: "[형] 충성스러운" },
  { eng: "humid", kor: "[형] 습한" },
  { eng: "pretend", kor: "[동] ~인 척하다" },
  { eng: "graduate", kor: "[동] 졸업하다 [명] 졸업생" },
  { eng: "delicate", kor: "[형] 연약한, 섬세한, 미묘한" },
  { eng: "inflate", kor: "[동] 부풀리다, 과장하다, (가격을) 올리다" },
  { eng: "adequate", kor: "[형] 적절한" },
  { eng: "physician", kor: "[명] 의사" },
  { eng: "joint", kor: "[명] 관절 [형] 공동의" },
  { eng: "via", kor: "[전] ~을 경유해서, ~을 매개로 하여" },
  { eng: "passage", kor: "[명] 통로, (책의) 구절" },
  { eng: "prefer", kor: "[동] ~을 좋아하다" },
  { eng: "vessel", kor: "[명] 선박, 용기" },
  { eng: "restore", kor: "[동] 이전상태로 회복시키다" },
  { eng: "passive", kor: "[형] 소극적인,수동적인" },
  { eng: "experience", kor: "[명] 경험 [동] 경험하다" },
  { eng: "marble", kor: "[명] 대리석" },
  { eng: "classify", kor: "[동] 분류하다" },
  { eng: "fundamental", kor: "[형] 근본적인, 필수의" },
  { eng: "majesty", kor: "[명] 위엄, 장엄, 왕(M-)" },
  { eng: "intimate", kor: "[형] 친밀한, 친숙한" },
  { eng: "merit", kor: "[명] 장점, 가치" },
  { eng: "launch", kor: "[동] 시작하다, 출시하다 [명] 발사, 출시" },
  { eng: "conference", kor: "[명] 회의" },
  { eng: "reception", kor: "[명] 접수처, 환영연회" },
  { eng: "shrug", kor: "[동] 어깨를 으쓱하다 [명] 어깨를 으쓱하기" },
  { eng: "vicious", kor: "[형] 악랄한, 타락한" },
  { eng: "cherish", kor: "[동] 소중히 하다" },
  { eng: "accuse", kor: "[동] 고발하다, 비난하다" },
  { eng: "eternal", kor: "[형] 영원한" },
  { eng: "shrink", kor: "[동] 줄어들다, 피하다" },
  { eng: "colleague", kor: "[명] 동료" },
  { eng: "transmit", kor: "[동] 보내다, 전염시키다, 전도하다" },
  { eng: "copper", kor: "[명] 구리 [형] 구리의, 구릿빛의" },
  { eng: "orbit", kor: "[명] 궤도 [동] 궤도를 그리며 돌다" },
  { eng: "overwhelm", kor: "[동] 압도하다, 당황하게 하다" },
  { eng: "discard", kor: "[동] 폐기하다, 버리다, 처분하다" },
  { eng: "famine", kor: "[명] 기근, 굶주림, 기아" },
  { eng: "pill", kor: "[명] 알약" },
  { eng: "enhance", kor: "[동] 강화하다" },
  { eng: "immune", kor: "[형] 면역의, 면역성이 있는" },
  { eng: "superior", kor: "[형] 뛰어난, 눈에 띄는" },
  { eng: "string", kor: "[명] 끈 [동] 끈을 달다" },
  { eng: "cope", kor: "[동] 대처하다" },
  { eng: "raw", kor: "[형] 날것의, 가공하지 않은" },
  { eng: "apply", kor: "[동] 지원하다, 적용되다" },
  { eng: "cattle", kor: "[명] 소" },
  { eng: "loan", kor: "[동] 빌려주다 [명] 대여, 융자금" },
  { eng: "obedient", kor: "[형] 유순한, 순종하는" },
  { eng: "procedure", kor: "[명] 절차, 수술" },
  { eng: "bond", kor: "[명] 유대, 속박 [동] 유대를 맺다" },
  { eng: "angle", kor: "[명] 각도, 각 [동] 비스듬히 움직이다" },
  { eng: "subtle", kor: "[형] 미묘한, 교묘한, 예민한" },
  { eng: "depict", kor: "[동] 묘사하다, 그리다" },
  { eng: "radical", kor: "[형] 근본적인, 급진적인" },
  { eng: "therapy", kor: "[명] 치료법" },
  { eng: "caution", kor: "[명] 조심, 경고 [동] 경고하다" },
  { eng: "persist", kor: "[동] 고집하다, 지속하다" },
  { eng: "reverse", kor: "[동] 뒤집다, 후진하다 [형] 반대의 [명] 반대, 후진" },
  { eng: "support", kor: "[명] 떠받치, 지지 [동] 지지하다, 후원하다" },
  { eng: "mammal", kor: "[명] 포유동물" },
  { eng: "iceberg", kor: "[명] 빙산" },
  { eng: "monetary", kor: "[형] 화폐의" },
  { eng: "revise", kor: "[동] 개정하다, 수정하다" },
  { eng: "resent", kor: "[동] 분개하다, 화를 내다" },
  { eng: "superb", kor: "[형] 매우 뛰어난" },
  { eng: "abrupt", kor: "[형] 갑작스런, 퉁명스러운" },
  { eng: "diverse", kor: "[형] 다양한" },
  { eng: "internal", kor: "[형] 내부의, 체내의" },
  { eng: "gloom", kor: "[명] 우울, 어둠" },
  { eng: "refine", kor: "[동] 개선하다, 정제하다" },
  { eng: "dynamic", kor: "[형] 역동적인, 활발한" },
  { eng: "nerve", kor: "[명] 신경" },
  { eng: "prompt", kor: "[형] 신속한, 즉각적인 [동] 촉발하다, 자극하다" },
  { eng: "suspend", kor: "[동] 일시 중지하다, 보류하다, 정직(정학)시키다" },
  { eng: "control", kor: "[동] 통제하다, 지배하다 [명] 통제, 지배" },
  { eng: "distraction", kor: "[명] 집중을 방해하는 것" },
  { eng: "collapse", kor: "[동] 무너지다, (가격이) 폭락하다" },
  { eng: "monologue", kor: "[명] 독백" },
  { eng: "martial", kor: "[형] 군대의, 전쟁의" },
  { eng: "deliberate", kor: "[형] 고의의, 신중한" },
  { eng: "trigger", kor: "[동] 작동시키다, 촉발시키다 [명] 방아쇠, 계기" },
  { eng: "plot", kor: "[명] 줄거리, 음모 [동] 음모를 꾸미다" },
  { eng: "rod", kor: "[명] 막대, 낚싯대" },
  { eng: "Atlantic", kor: "[명] 대서양 [형] 대서양의" },
  { eng: "industry", kor: "[명] 산업" },
  { eng: "weird", kor: "[형] 이상한, 괴상한" },
  { eng: "suggest", kor: "[동] 제안하다, 암시하다" },
  { eng: "partial", kor: "[형] 부분적인, 편파적인" },
  { eng: "priceless", kor: "[형] 대단히 소중한" },
  { eng: "mutual", kor: "[형] 상호 간의, 공동의" },
  { eng: "fate", kor: "[명] 운명" },
  { eng: "booth", kor: "[명] 작은 공간" },
  { eng: "pursue", kor: "[동] 추구하다" },
  { eng: "prescribe", kor: "[동] 처방하다, 규정하다" },
  { eng: "erupt", kor: "[동] (화산이) 폭발하다" },
  { eng: "insult", kor: "[동] 모욕하다 [명] 모욕, 모욕적인 말" },
  { eng: "gaze", kor: "[동] 응시하다 [명] 응시" },
  { eng: "supreme", kor: "[명] 최고 [형] 최고의" },
  { eng: "transaction", kor: "[명] 거래, 매매" },
  { eng: "sufficient", kor: "[형] 충분한" },
  { eng: "stable", kor: "[형] 안정된 [명] 마구간" },
  { eng: "sympathy", kor: "[명] 연민, 동의" },
  { eng: "by-product", kor: "[명] 부산물" },
  { eng: "edible", kor: "[형] 먹을 수 있는" },
  { eng: "federal", kor: "[형] 연방의, 연방 정부의" },
  { eng: "bud", kor: "[명] 싹, 봉오리, 친구" },
  { eng: "trivial", kor: "[형] 사소한" },
  { eng: "anxiety", kor: "[명] 걱정, 불안, 열망" },
  { eng: "tablet", kor: "[명] 알약" },
  { eng: "prepare", kor: "[동] 준비하다" },
  { eng: "trade", kor: "[명] 무역하다, 교환하다" },
  { eng: "liquid", kor: "[명] 액체 [형] 액체의, 유동적의" },
  { eng: "contend", kor: "[동] 싸우다, 주장하다" },
  { eng: "outlook", kor: "[명] 전망, 경치, 견해" },
  { eng: "roam", kor: "[동] 배회하다, 돌아다니다" },
  { eng: "decent", kor: "[형] 괜찮은, 예의 바른, 적절한" },
  { eng: "concern", kor: "[명] 걱정, 관심 [동] 걱정하다, 관심을 갖다" },
  { eng: "behalf", kor: "[명] 측, 편, 이익" },
  { eng: "suffer", kor: "[동] 고통 받다, 겪다" },
  { eng: "distortion", kor: "[명] 왜곡, 찌그러뜨림" },
  { eng: "infinite", kor: "[형] 무한한" },
  { eng: "anticipate", kor: "[동] 예상하다, 기대하다" },
  { eng: "symbolic", kor: "[형] 상징적인" },
  { eng: "municipal", kor: "[형] 지방 자치제의" },
  { eng: "phenomenon", kor: "[명] 현상" },
  { eng: "devote", kor: "[동] (시간, 노력)쏟다" },
  { eng: "peasant", kor: "[명] 소작농" },
  { eng: "tenant", kor: "[명] 세입자" },
  { eng: "worthwhile", kor: "[형] 가치있는" },
  { eng: "pavement", kor: "[명] 포장도로" },
  { eng: "dioxide", kor: "[명] (화학)이산화물" },
  { eng: "diminish", kor: "[동] 줄이다, 약화시키다" },
  { eng: "jealous", kor: "[형] 질투하는, 시기하는" },
  { eng: "limp", kor: "[형] 기운이 없는, 축 처진" },
  { eng: "exclude", kor: "[동] 제외하다, 차단하다" },
  { eng: "flexible", kor: "[형] 융통성 있는, 잘 구부러지는" },
  { eng: "nominate", kor: "[동] 지명하다" },
  { eng: "sacred", kor: "[형] 성스러운, 종교적인" },
  { eng: "context", kor: "[명] 맥락" },
  { eng: "complete", kor: "[형] 완벽한[동] 완료하다" },
  { eng: "race", kor: "[명] 경주, 인종[동] 경주하다" },
  { eng: "dominate", kor: "[동] 지배하다" },
  { eng: "vehicle", kor: "[명] 탈것" },
  { eng: "complain", kor: "[동] 불평하다" },
  { eng: "brochure", kor: "[명] 브로셔" },
  { eng: "force", kor: "[명] 힘[동] 강요하다" },
  { eng: "nest", kor: "[명] 둥지" },
  { eng: "gain", kor: "[동] 얻다" },
  { eng: "curriculum", kor: "[명] 교육 과정" },
  { eng: "sew", kor: "[동] 바느질하다" },
  { eng: "masculine", kor: "[형] 남자의" },
  { eng: "frown", kor: "[동] 눈살을 찌푸리다[명] 찡그린 얼굴" },
  { eng: "astound", kor: "놀라게 하다" },
  { eng: "dictator", kor: "[명] 독재자" },
  { eng: "assessment", kor: "[명] 평가" },
  { eng: "crucial", kor: "[형] 중대한, 결정적인" },
  { eng: "paralysis", kor: "[명] 마비" },
  { eng: "deck", kor: "[명] (배의) 갑판" },
  { eng: "cheer", kor: "[명] 환호[동] 환호하다" },
  { eng: "miserable", kor: "[형] 비참한" },
  { eng: "tease", kor: "[동] 괴롭히다" },
  { eng: "aggressive", kor: "[형] 공격적인" },
  { eng: "cure", kor: "[동] 치료하다[명] 치료" },
  { eng: "attribute", kor: "[동] ~의 결과로 여기다[명] 속성" },
  { eng: "foster", kor: "[동] 육성하다" },
  { eng: "phychologist", kor: "심리학자" },
  { eng: "postpone", kor: "[동] 연기하다" },
  { eng: "rob", kor: "[동] 강탈하다, 훔치다" },
  { eng: "abuse", kor: "[동] 남용하다, 학대하다[명] 남용, 학대" },
  { eng: "unemployed", kor: "[형] 실업의" },
  { eng: "breakdown", kor: "[명] 고장, 쇠약" },
  { eng: "disguise", kor: "[동] 숨기다, 변장" },
  { eng: "blueprint", kor: "[명] 청사진" },
  { eng: "rear", kor: "[형] 뒤의[명] 뒤[동] 기르다" },
  { eng: "output", kor: "[명] 생산량" },
  { eng: "sermon", kor: "[명] 설교" },
  { eng: "sprout", kor: "[동] 싹이 트다. 싹" },
  { eng: "tin", kor: "[명] 주석, 양철" },
  { eng: "reform", kor: "[동] 개혁하다[명] 개혁," },
  { eng: "deal", kor: "[동] 다루다[명] 거래" },
  { eng: "recruit", kor: "[동] 모집하다[명] 신병" },
  { eng: "maintain", kor: "[동] 유지하다" },
  { eng: "workshop", kor: "[명] 작업장, 워크숍" },
  { eng: "patient", kor: "[명] 환자" },
  { eng: "convention", kor: "[명] 총회, 관습" },
  { eng: "devastate", kor: "[동] 황폐시키다" },
  { eng: "reap", kor: "[동] 수확하다" },
  { eng: "overlook", kor: "[동] 간과하다, 내려다보다" },
  { eng: "deliver", kor: "[동] 배달하다, (연설을)하다" },
  { eng: "reject", kor: "[동] 거부하다, 거절하다" },
  { eng: "nourish", kor: "[동] 영양분을 주다, 기르다" },
  { eng: "bay", kor: "[명] 만" },
  { eng: "stun", kor: "[동] 놀라게 하다" },
  { eng: "particular", kor: "[형] 특정한" },
  { eng: "bulletin", kor: "[명] 게시(물)" },
  { eng: "fluid", kor: "[형] 유동성의[명] 유동체" },
  { eng: "affair", kor: "[명] 일, 사건" },
  { eng: "dawn", kor: "[명] 새벽, 시작[동] 날이 새다" },
  { eng: "hostile", kor: "[형] 적대적인" },
  { eng: "characteristic", kor: "[명] 특징" },
  { eng: "respect", kor: "[동] 존경하다, (법 등을) 준수하다[명] 존경, 측면" },
  { eng: "await", kor: "[동] 기다리다" },
  { eng: "concrete", kor: "[형] 구체적인" },
  { eng: "lease", kor: "[동] 임대하다[명] 임대차 계약" },
  { eng: "racial", kor: "[형] 인종의" },
  { eng: "variable", kor: "[형] 변수. 변하기 쉬운, 변덕스러운" },
  { eng: "satisfy", kor: "[동] 만족시키다" },
  { eng: "rule", kor: "[명] 규칙, 지배[동] 지배하다" },
  { eng: "perseverance", kor: "인내심" },
  { eng: "fatal", kor: "[형] 치명적인" },
  { eng: "remove", kor: "[동] 제거하다, 치우다" },
  { eng: "invert", kor: "거꾸로 하다" },
  { eng: "tension", kor: "[명] 긴장" },
  { eng: "reign", kor: "[명] 통치, 지배" },
  { eng: "crack", kor: "[명] 금이 가다[명] (갈라진 틈" },
  { eng: "startle", kor: "[동] 깜짝 놀라게 하다" },
  { eng: "discourage", kor: "[동] 낙담시키다, 말리다" },
  { eng: "compensate", kor: "[동] 보상하다" },
  { eng: "convert", kor: "[동] 전환시키다, 바꾸다" },
  { eng: "strike", kor: "[동] 치다" },
  { eng: "suppress", kor: "[동] 억압하다, 참다" },
  { eng: "core", kor: "[명] 핵심(의)" },
  { eng: "contribute", kor: "[동] 공헌하다" },
  { eng: "spear", kor: "[명] 창" },
  { eng: "renowned", kor: "[형] 명성 있는" },
  { eng: "era", kor: "[명] 시대" },
  { eng: "withdraw", kor: "[동] 인출하다" },
  { eng: "immigrate", kor: "[동] 이주하다" },
  { eng: "dignity", kor: "[명] 존엄" },
  { eng: "notify", kor: "[동] 통보하다, 알리다" },
  { eng: "animate", kor: "살아 있는" },
  { eng: "prevent", kor: "[동] 예방하다, 막다" },
  { eng: "bilingual", kor: "[형] 2개 국어의" },
  { eng: "mischief", kor: "장난, 해악" },
  { eng: "discriminate", kor: "[동] 차별하다, 구별하다" },
  { eng: "exemplify", kor: "[동] 예시하다" },
  { eng: "adhere", kor: "[동] 고수하다" },
  { eng: "judge", kor: "[동] 판단하다" },
  { eng: "peculiar", kor: "[형] 독특한" },
  { eng: "sake", kor: "[명] 위함, 목적" },
  { eng: "choke", kor: "[동] 질식시키다" },
  { eng: "folktale", kor: "민간 설화, 전설" },
  { eng: "simultaneously", kor: "[부] 동시에" },
  { eng: "range", kor: "[명] 범위" },
  { eng: "groom", kor: "신랑" },
  { eng: "supernatural", kor: "[형] 초자연적인" },
  { eng: "tender", kor: "[형] 부드러운" },
  { eng: "instinct", kor: "[명] 본능" },
  { eng: "gigantic", kor: "[형] 거대한" },
  { eng: "meditate", kor: "명상하다" },
  { eng: "mow", kor: "[동] (풀을) 베다" },
  { eng: "evolve", kor: "[동] 진화하다, 발전하다" },
  { eng: "chase", kor: "[동] 추격하다, 쫓다" },
  { eng: "afflict", kor: "[동] 괴롭히다" },
  { eng: "literate", kor: "읽고 쓸 수 있는" },
  { eng: "coherent", kor: "[형] 통일성 있는, 조리 있는" },
  { eng: "intolerable", kor: "참을 수 없는" },
  { eng: "fountain", kor: "[명] 분수" },
  { eng: "bold", kor: "[형] 대담한, 선이 굵은" },
  { eng: "compliment", kor: "[동] 칭찬하다[명] 칭찬" },
  { eng: "summit", kor: "[명] 정상" },
  { eng: "troop", kor: "[명] 무리, 군대" },
  { eng: "alter", kor: "[동] 바꾸다, 변경하다" },
  { eng: "conceive", kor: "[동] 생각해 내다" },
  { eng: "durability", kor: "내구성" },
  { eng: "destroy", kor: "[동] 파괴하다" },
  { eng: "shallow", kor: "[형] 얕은, 피상적인" },
  { eng: "face", kor: "[명] 얼굴, 표면[동] 직면하다" },
  { eng: "promote", kor: "[동] 승진시키다" },
  { eng: "weep", kor: "[동] 울다" },
  { eng: "grasp", kor: "[동] 붙잡다" },
  { eng: "overall", kor: "[형] 전반적인, 전체의" },
  { eng: "superstition", kor: "[명] 미신" },
  { eng: "colony", kor: "[명] 식민지" },
  { eng: "absurd", kor: "[형] 불합리한, 우스꽝스러운" },
  { eng: "dormitory", kor: "[명] 기숙사" },
  { eng: "conduct", kor: "[동] 수행하다[명] 행위" },
  { eng: "prone", kor: "[형] ~하는 경향이 있는" },
  { eng: "conceal", kor: "[동] 숨기다" },
  { eng: "retreat", kor: "[동] 후퇴하다[명] 후퇴" },
  { eng: "compulsive", kor: "강제적인, 강박의" },
  { eng: "clinic", kor: "[명] 전문 병원, 개인 병원" },
  { eng: "banner", kor: "[명] 현수막" },
  { eng: "formulate", kor: "[동] 만들어내다, 공식화하다" },
  { eng: "vow", kor: "[명] 맹세(하다)" },
  { eng: "malnutrition", kor: "영양실조" },
  { eng: "relate", kor: "[동] 관련시키다" },
  { eng: "undergo", kor: "[동] 겪다" },
  { eng: "boast", kor: "[동] 자랑하다" },
  { eng: "neutral", kor: "[형] 중립의" },
  { eng: "stain", kor: "[명] 얼룩" },
  { eng: "incentive", kor: "[명] 장려책, 자극" },
  { eng: "float", kor: "[동] 뜨다, 떠다니다" },
  { eng: "tendency", kor: "[명] 경향" },
  { eng: "applause", kor: "[명] 박수갈채" },
  { eng: "wrestle", kor: "[동] 싸우다, 씨름하다" },
  { eng: "sensation", kor: "[명] 감각, 느낌" },
  { eng: "Confucian", kor: "공자의, 유교의" },
  { eng: "diameter", kor: "[명] 지름" },
  { eng: "ultrasound", kor: "[명] 초음파" },
  { eng: "propriety", kor: "[명] 적절성, 예의바름" },
  { eng: "anecdote", kor: "[명] 일화" },
  { eng: "shrub", kor: "[명] 관목" },
  { eng: "pledge", kor: "[명] 서약, 담보 [동] 서약하다" },
  { eng: "cost", kor: "[명] 가격, 비용 [동] (가격, 비용이) 들다" },
  { eng: "geology", kor: "[명] 지질학" },
  { eng: "detect", kor: "[동] 찾아내다, 감지하다" },
  { eng: "temperate", kor: "[형] 절제하는, (기후가) 온화한" },
  { eng: "soar", kor: "[동] 급등하다, 날아오르다" },
  { eng: "mock", kor: "[동] 놀리다, 조롱하다 [형] 가짜의, 모조의" },
  { eng: "disclose", kor: "[동] 폭로하다, 드러내다" },
  { eng: "exhibit", kor: "[동] 전시하다 [명] 전시품" },
  { eng: "symptom", kor: "[명] 증상, 증후" },
  { eng: "manage", kor: "[동] 경영하다, 관리하다, 간신히 해내다" },
  { eng: "awkward", kor: "[형] 어색한, 서투른, 다루기 힘든" },
  { eng: "grind", kor: "[동] 갈다" },
  { eng: "expose", kor: "[동] 노출시키다, 폭로하다" },
  { eng: "closet", kor: "[명] 벽장" },
  { eng: "damp", kor: "[형] 축축한" },
  { eng: "script", kor: "[명] 대본" },
  { eng: "possibility", kor: "[명] 가능성, 기회" },
  { eng: "fad", kor: "[명] (일시적인) 유행" },
  { eng: "sibling", kor: "[명] 형제, 자매" },
  { eng: "linger", kor: "[동] 남아 있다, 어슬렁거리다" },
  { eng: "flourish", kor: "[동] 번성하다, 건강하다" },
  {
    eng: "discharge",
    kor: "[동] 해고하다, 방출하다, 방면하다 [명] 해고, 방출, 면제",
  },
  { eng: "thorough", kor: "[형] 철저한" },
  { eng: "undertake", kor: "[동] 착수하다, 약속하다" },
  {
    eng: "cord",
    kor: "[명] 끈, 전기코드, (직물)코르덴 천 [형] 코르덴 천으로 만들어진",
  },
  { eng: "linguistic", kor: "[형] 언어의, 언어학의" },
  { eng: "remedy", kor: "[명] 치료" },
  { eng: "sole", kor: "[형] 유일한, 단독의" },
  { eng: "sophomore", kor: "[명] (고교, 대학의) 2학년생" },
  { eng: "panel", kor: "[명] 판" },
  { eng: "suitor", kor: "[명] 소송인, 구혼자" },
  { eng: "pillar", kor: "[명] 기둥" },
  { eng: "explode", kor: "[동] 폭발하다" },
  { eng: "illusion", kor: "[명] 착각, 환각" },
  { eng: "draft", kor: "[명] 초고, 초안 [동] 초안을 그리다" },
  { eng: "crude", kor: "[형] 조잡한, 있는 그대로의" },
  { eng: "supplement", kor: "[동] 보완하다 [명] 보완, 보충" },
  { eng: "velocity", kor: "[명] 속도" },
  { eng: "tame", kor: "[동] 길들이다 [형] 길들여진" },
  { eng: "molecule", kor: "[명] 분자" },
  { eng: "reed", kor: "[명] 갈대 [형] 갈대의" },
  { eng: "dismay", kor: "[명] 실망 [동] 크게 실망시키다" },
  { eng: "diagnose", kor: "[동] 진단하다" },
  { eng: "versus", kor: "[전] ~와 대비하여" },
  { eng: "reservoir", kor: "[명] 저수지" },
  { eng: "conform", kor: "[동] 따르다, 순응하다" },
  { eng: "spacious", kor: "[형] 넓은, 훤히 트인" },
  { eng: "weave", kor: "[동] (천을) 짜다 [명] 짜기" },
  { eng: "ceremony", kor: "[명] 의식, 식" },
  { eng: "motive", kor: "[명] 동기, 이유" },
  { eng: "prominent", kor: "[형] 두드러진" },
  { eng: "archaeology", kor: "[명] 고고학" },
  { eng: "rigid", kor: "[형] 엄격한, 굳은" },
  { eng: "inferior", kor: "[형] 열등한, 질 낮은" },
  { eng: "subtract", kor: "[동] 빼다" },
  { eng: "impulse", kor: "[명] 충동, 욕구, 추진력" },
  { eng: "utmost", kor: "[형] 최대한의  [명] 최대한도" },
  { eng: "proficient", kor: "[형] 숙달된" },
  { eng: "accumulate", kor: "[동] 모으다, 축적하다" },
  { eng: "navigate", kor: "[동] 길을 찾다, 항해하다" },
  { eng: "equity", kor: "[명] 자기자본, 공평" },
  { eng: "violate", kor: "[동] 위반하다, 침해하다" },
  { eng: "ambitious", kor: "[형] 야망을 가진" },
  { eng: "intact", kor: "[형] 온전한, 손상되지 않은" },
  { eng: "plea", kor: "[명] 애원, 탄원" },
  { eng: "attend", kor: "[동] 참석하다, 유의하다, 돌보다" },
  { eng: "trim", kor: "[동] 다듬다 [형] 잘 정돈된 [명] 정돈" },
  { eng: "embody", kor: "[동] 구체화하다, 포함하다" },
  { eng: "characteristic", kor: "[명] 특징, 특성 [형] 특유의" },
  { eng: "consist", kor: "[동] ~로 구성되다" },
  { eng: "boundary", kor: "[명] 경계, 한계" },
  { eng: "attack", kor: "[동] 공격하다 [명] 공격" },
  { eng: "confine", kor: "[동] 제한하다, 가두다" },
  { eng: "dispatch", kor: "[명] 급파, 발송 [동] 파견하다, 발송하다" },
  { eng: "regret", kor: "[동] 후회하다[명] 후회" },
  { eng: "coffin", kor: "[명] 관" },
  { eng: "divine", kor: "[형] 신성한" },
  { eng: "revenue", kor: "[명] 수익" },
  { eng: "corrupt", kor: "[형] 부패한, 타락한[동] 부패하다, 타락하다" },
  { eng: "probe", kor: "[동] 조사하다, 연구하다[명] 조사" },
  { eng: "factual", kor: "[형] 실제의" },
  { eng: "swamp", kor: "[명] 늪, 습지" },
  { eng: "expedition", kor: "[명] 탐험" },
  { eng: "abnormal", kor: "[형] 이상한, 비정상의" },
  { eng: "storage", kor: "[명] 저장소, 저장" },
  { eng: "revive", kor: "[동] 되살아나다" },
  { eng: "stool", kor: "[명] (등받이 없는) 의자" },
  { eng: "hinder", kor: "[동] 방해하다" },
  { eng: "flattery", kor: "[명] 아첨" },
  { eng: "virtue", kor: "[명] 미덕" },
  { eng: "deadline", kor: "[명] 기한, 마감시간" },
  { eng: "equator", kor: "n.적도" },
  { eng: "cognitive", kor: "[형] 인식의" },
  { eng: "motion", kor: "[명] 운동, 동작[동] 동작을 해 보이다" },
  { eng: "humble", kor: "[형] 겸손한, 비천한" },
  { eng: "bounce", kor: "[동] 튀어 오르다, 깡충깡충 뛰다, (공이) 튀다" },
  { eng: "imprison", kor: "[동] 투옥하다" },
  { eng: "enlist", kor: "[동]모집하다" },
  { eng: "hygiene", kor: "[명] 위생, 위생학" },
  { eng: "upcoming", kor: "[형] 다가오는" },
  { eng: "trace", kor: "[명] 자취, 흔적[동] 추적하다, 밝혀내다" },
  { eng: "pulse", kor: "[명] 맥박" },
  { eng: "controversy", kor: "[명] 논쟁, 언쟁, 논란" },
  { eng: "locate", kor: "[동] (장소를) 찾아내다, -에 위치하다" },
  { eng: "patent", kor: "[명] 특허[형] 특허를 받은[동] 특허권을 얻다" },
  { eng: "lyric", kor: "n.가사" },
  { eng: "convenience", kor: "[명] 편의, 편리, 편의시설" },
  { eng: "rush", kor: "[동] 돌진하다, 급하게 가다[명] 돌진, 혼잡" },
  { eng: "carbon", kor: "[명] 탄소" },
  { eng: "contaminate", kor: "[동] 오염시키다, 더럽히다" },
  { eng: "external", kor: "[형] 외부의" },
  { eng: "herd", kor: "[명] 떼, 무리[동] 떼를 짓다" },
  { eng: "allocate", kor: "[동] 할당하다, 배분하다" },
  { eng: "gorgeous", kor: "[형] 아주 멋진, 화려한" },
  { eng: "confess", kor: "[동] 고백하다" },
  { eng: "subjective", kor: "[형] 주관적인" },
  { eng: "hell", kor: "[명] 지옥" },
  { eng: "acknowledge", kor: "[동] 인정하다" },
  { eng: "accord", kor: "[동] 일치하다, 조화하다[명] 일치, 합의" },
  { eng: "immense", kor: "[형] 엄청난" },
  { eng: "extract", kor: "[동] 추출하다, [명] 추출물" },
  { eng: "sewage", kor: "[명] 하수, 오물" },
  { eng: "reconciliation", kor: "[명] 화해" },
  { eng: "amid", kor: "[전] ~의 한가운데" },
  { eng: "warrant", kor: "[명] 보증서, 영장, 정당한 이유" },
  { eng: "complement", kor: "[동] 보완하다" },
  { eng: "ceramic", kor: "[명] 도자기, 요업" },
  { eng: "license", kor: "[명] 면허, 인가[동] 면허를 주다, 허가하다" },
  { eng: "emerge", kor: "[동] 나타나다" },
  { eng: "halt", kor: "[동] 정지시키다[명] 정지, 멈춤" },
  { eng: "ivory", kor: "[명] 상아, 상아색" },
  { eng: "ponder", kor: "[동] 곰곰이 생각하다, 심사숙고하다" },
  { eng: "lottery", kor: "[명] 복권, 추첨" },
  { eng: "stroke", kor: "[명] 타격, 뇌졸증" },
  { eng: "burglar", kor: "[명] 강도" },
  { eng: "blame", kor: "[동] 비난하다, ~을 탓하다[명] 비난" },
  { eng: "transplant", kor: "[동]  이식하다" },
  { eng: "cluster", kor: "[명] 무리" },
  { eng: "borrow", kor: "[동] 빌리다" },
  { eng: "derive", kor: "[동] 끌어내다, ~에서 비롯되다" },
  { eng: "plague", kor: "[명] 전염병[동] 괴롭히다" },
  { eng: "certificate", kor: "[명] 증명서" },
  { eng: "deluxe", kor: "호화로운" },
  { eng: "convey", kor: "[동] 나르다,전달하다, (생각, 감정을) 전하다" },
  { eng: "depth", kor: "[명] 깊이" },
  { eng: "evaporate", kor: "[동] 증발하다" },
  { eng: "lame", kor: "[형] 절름발이의, 설득력이 없는" },
  { eng: "conduct", kor: "[동] 실시하다, 수행하다, 행동하다[명] 행위" },
  { eng: "sour", kor: "[형] (맛이)신" },
  { eng: "repetitive", kor: "[형] 반복성의" },
  { eng: "oppress", kor: "n.억압하다" },
  { eng: "leftover", kor: "[명] 남은 음식, 잔재" },
  { eng: "embrace", kor: "[동] 포옹하다, 껴안다, 수용하다" },
  { eng: "blade", kor: "[명] 칼날" },
  { eng: "abundant", kor: "[형] 풍부한" },
  { eng: "duplicate", kor: "[형] 똑같은[동] 복사하다[명] 사본" },
  { eng: "remind", kor: "[동] 상기시키다, 생각나게 하다" },
  { eng: "altitude", kor: "[명] 고도" },
  { eng: "glimpse", kor: "[동] 흘끗 보다[명] 흘끗 봄" },
  { eng: "blend", kor: "[동] 섞다" },
  { eng: "swell", kor: "[동] 부풀다,[명] 팽창" },
  { eng: "grief", kor: "[명] 비탄, 큰 슬픔" },
  { eng: "beverage", kor: "[명] 음료수" },
  { eng: "warrior", kor: "[명] 전사, 용사" },
  { eng: "earn", kor: "[동] (평판을) 얻다, 벌다" },
  { eng: "slice", kor: "[명] (얇게 썬)조각[동] 얇게 썰다" },
  { eng: "exotic", kor: "[형] 이국적인" },
  { eng: "arrogant", kor: "[형] 거만한, 건방진" },
  { eng: "vanish", kor: "[동] 사라지다" },
  { eng: "rational", kor: "[형] 이성적인, 합리적인" },
  { eng: "predominant", kor: "[형] 우세한, 두드러진" },
  { eng: "cozy", kor: "[형] 안락한, 아늑한" },
  { eng: "broker", kor: "[명] 중개인, 브로커[동] 중개하다" },
  { eng: "auction", kor: "[명] 경매[동] 경매로 팔다" },
  { eng: "obsess", kor: "v.사로잡다, 강박 관념을 갖다" },
  { eng: "feed", kor: "[동] ~에 밥을 주다, ~에 먹이를 주다" },
  { eng: "outbreak", kor: "[명] (전쟁, 사고등의) 발발" },
  { eng: "invent", kor: "[동] 발명하다" },
  { eng: "pioneer", kor: "[명] 개척자[동] 개척하다" },
  { eng: "assert", kor: "[동] 주장하다" },
  { eng: "undo", kor: "[동] (잠긴 것을) 풀다, 원상태로 돌리다" },
  { eng: "bouquet", kor: "[명] 꽃다발" },
  { eng: "elaborate", kor: "[형] 정교한" },
  { eng: "toss", kor: "[동] 던지다[명] 던지기" },
  { eng: "retain", kor: "[동] 보유하다" },
  { eng: "radioactive", kor: "[형] 방사능의" },
  { eng: "buildup", kor: "[명] 축적" },
  { eng: "machinery", kor: "[명] 기계" },
  { eng: "passerby", kor: "통행인" },
  { eng: "auditorium", kor: "[명] 강당" },
  { eng: "lay", kor: "[동] 놓다, (알을) 낳다" },
  { eng: "neglect", kor: "[동] 무시하다[명] 소홀" },
  { eng: "feedback", kor: "[명] 피드백" },
  { eng: "promote", kor: "[동] 증진하다, 승진시키다" },
  { eng: "impair", kor: "[동] 손상시키다" },
  { eng: "metaphor", kor: "[명] 은유" },
  { eng: "dispense", kor: "[동] 분배하다, 나누어 주다" },
  { eng: "bruise", kor: "[명] 멍, 타박상" },
  { eng: "attorney", kor: "[명] 변호사, 대리인" },
  { eng: "framework", kor: "[명] 뼈대, 틀, 체제" },
  { eng: "heredity", kor: "n.유전" },
  { eng: "naive", kor: "[형] 순진한" },
  { eng: "shed", kor: "v.떨구다, 흘리다" },
  { eng: "metropolitan", kor: "[형] 대도시의" },
  { eng: "shield", kor: "[명] 방패[동] 보호하다" },
  { eng: "induce", kor: "[동] 유도하다, 설득하여 ~시키다" },
  { eng: "bazaar", kor: "시장, 바자" },
  { eng: "expel", kor: "[동] 추방하다" },
  { eng: "plow", kor: "[명] 쟁기[동] 갈다" },
  { eng: "prolong", kor: "[동] 연장하다" },
  { eng: "fluent", kor: "유창한" },
  { eng: "margin", kor: "[명] 가장자리" },
  { eng: "ecology", kor: "[명] 생태학, 생태" },
  { eng: "interior", kor: "[명] 내부[형] 내부의" },
  { eng: "ornament", kor: "[명] 장식[동] 장식하다" },
  { eng: "separate", kor: "[동] 분리하다" },
  { eng: "ripe", kor: "[형] 익은" },
  { eng: "vibrate", kor: "[동] 진동하다, 흔들다" },
  { eng: "urgent", kor: "[형] 긴급한" },
  { eng: "speculate", kor: "[동] 사색하다 ,투기하다" },
  { eng: "epidemic", kor: "[명] 전염병" },
  { eng: "precede", kor: "[동] ~에 앞서다" },
  { eng: "breathtaking", kor: "숨막히는" },
  { eng: "portfolio", kor: "[명] 포트폴리오" },
  { eng: "beware", kor: "[동] 주의하다" },
  { eng: "handcuff", kor: "[n] 수갑" },
  { eng: "overturn", kor: "[동] 전복시키다[명] 전복" },
  { eng: "pregnant", kor: "[형] 임신한" },
  { eng: "intelligence", kor: "[명] 지능" },
  { eng: "adapt", kor: "[동] 적응시키다" },
  { eng: "settle", kor: "[동] 정착하다" },
  { eng: "assassinate", kor: "[동] 암살하다" },
  { eng: "vapor", kor: "[명] 증기" },
  { eng: "tuition", kor: "[명] 수업료" },
  { eng: "literature", kor: "[명] 문학" },
  { eng: "loop", kor: "[명] 고리[동] 고리로 만들다" },
  { eng: "quote", kor: "[동] 인용하다[명] 인용구" },
  { eng: "inhale", kor: "[동] 들이쉬다, 흡입하다" },
  { eng: "prospect", kor: "[명] 전망, 가능성" },
  { eng: "anchor", kor: "[명] 닻,앵커" },
  { eng: "reference", kor: "[명] 참고, 언급" },
  { eng: "compound", kor: "[동] 혼합하다[명] 혼합물[형] 합성의" },
  { eng: "withstand", kor: "[동] 견디다, 버티다" },
  { eng: "implement", kor: "[동] 실행하다[명] 도구" },
  { eng: "anonymous", kor: "[형] 익명의" },
  { eng: "collide", kor: "[동] 충돌하다, 일치하지 않다" },
  { eng: "memorial", kor: "[명] 기념물" },
  { eng: "vacant", kor: "[형] 비어 있는, 빈자리의" },
  { eng: "technical", kor: "[형] 기술의" },
  { eng: "summon", kor: "[동] 소환하다" },
  { eng: "orchard", kor: "[명] 과수원" },
  { eng: "proportion", kor: "[명] 비율, 부분" },
  { eng: "antibiotic", kor: "[명] 항생 물질" },
  { eng: "overtake", kor: "[동] 따라잡다" },
  { eng: "resemble", kor: "[동] ~와 닮다" },
  { eng: "wander", kor: "[동] (정처없이) 돌아다니다, 헤매다" },
  { eng: "compassion", kor: "[명] 동정" },
  { eng: "preoccupation", kor: "[명] 몰두, 집착" },
  { eng: "paste", kor: "[동] 풀로 붙이다[명] 풀" },
  { eng: "provoke", kor: "[동] 선동하다, 자극하다" },
  { eng: "wicked", kor: "[형] 사악한, 심술궂은" },
  { eng: "sprain", kor: "발목을 삐다" },
  { eng: "propaganda", kor: "[명] 선전" },
  { eng: "consistent", kor: "[형] 일관된" },
  { eng: "disrupt", kor: "[동] 붕과시키다" },
  { eng: "solitary", kor: "[형] 혼자의, 고립된" },
  { eng: "bury", kor: "[동] (땅에)묻다" },
  { eng: "rust", kor: "[명] 녹[동] 녹이 슬다, 부식하다" },
  { eng: "discuss", kor: "[동] 토론하다" },
  { eng: "referee", kor: "[명] 심판" },
  { eng: "sector", kor: "[명] 분야, 지역" },
  { eng: "boost", kor: "[동] 밀어올리다[명] 상승" },
  { eng: "gymnastics", kor: "[명] 체조" },
  { eng: "gross", kor: "[형] 총합의[명] 총합" },
  { eng: "last", kor: "[형] 마지막, 지난" },
  { eng: "tariff", kor: "[명] 관세, 운임표" },
  { eng: "beloved", kor: "[형] 총애받는, 사랑하는" },
  { eng: "lyric", kor: "[명] 가사" },
  { eng: "yeast", kor: "[명] 이스트, 효모" },
  { eng: "skyscraper", kor: "[명] 고층건물" },
  { eng: "inquire", kor: "[동] 묻다" },
  { eng: "spade", kor: "[명] 삽, 스페이드" },
  { eng: "vacuum", kor: "[명] 진공, 공백" },
  { eng: "migrate", kor: "[동] 이주하다, 이동하다" },
  { eng: "spectacle", kor: "[명] 구경거리, 장관" },
  { eng: "surplus", kor: "[명] 여분, 나머지 [형] 나머지의" },
  { eng: "simulate", kor: "[동] 흉내내다, ~의 모의 실험을 하다" },
  { eng: "integration", kor: "[명] 통합" },
  { eng: "hypothesis", kor: "[명] 가설, 가정" },
  { eng: "affirm", kor: "[동] 단언하다" },
  { eng: "fortress", kor: "[명] 요새" },
  { eng: "reed", kor: "[명] 갈대" },
  { eng: "cue", kor: "[명] 신호, 단서 [동] 신호를 주다" },
  { eng: "mole", kor: "[명] 반점, 두더지" },
  { eng: "divide", kor: "[동] 나누다" },
  { eng: "inborn", kor: "타고난" },
  { eng: "overlap", kor: "[동] 겹치다, 중복되다" },
  { eng: "fatique", kor: "[명] 피곤" },
  { eng: "clone", kor: "[명] 복제, 복제품 [동] 복제하다" },
  { eng: "peel", kor: "[동] 껍질을 벗기다" },
  { eng: "ease", kor: "[명] 쉬움, 편안함 [동] 편하게 하다, 완화하다" },
  { eng: "overcome", kor: "[동] 극복하다" },
  { eng: "fund", kor: "[명] 자금" },
  { eng: "bias", kor: "[명] 편견, 선입견" },
  { eng: "vaccine", kor: "[명] 백신" },
  { eng: "tread", kor: "[동] 밟다 [명] 밟기" },
  { eng: "vomit", kor: "[동] 구토하다 [명] 구토" },
  { eng: "prophecy", kor: "[명] 예언" },
  { eng: "correspond", kor: "[동] 일치하다, 해당하다, 편지를 주고받다" },
  { eng: "cling", kor: "[동] 꼭 붙잡다, 달라붙다" },
  { eng: "mutation", kor: "[명] 돌연변이, 변형" },
  { eng: "obscure", kor: "[형] 모호한, 잘 알려지지 않은 [동] 모호하게 하다" },
  { eng: "tyrant", kor: "[명] 폭군" },
  { eng: "odd", kor: "[형] 이상한, 홀수의" },
  { eng: "intriguing", kor: "[형] 아주 흥미로운" },
  { eng: "restrain", kor: "[동] 억제하다, 제지하다" },
  { eng: "bundle", kor: "[명] 묶음" },
  { eng: "enclose", kor: "[동] 동봉하다, 둘러싸다" },
  { eng: "insert", kor: "[동] 삽입하다, 덧붙이다" },
  { eng: "keen", kor: "[형] 예민한, ~을열망하는" },
  { eng: "constrict", kor: "[동] 수축시키다" },
  { eng: "aid", kor: "[명] 도움, 지원" },
  { eng: "reputation", kor: "[명] 명성" },
  { eng: "measurement", kor: "[명] 측정" },
  { eng: "originate", kor: "[동] 유래하다" },
  { eng: "flour", kor: "[명] 밀가루" },
  { eng: "manipulate", kor: "[동] 조작하다, 잘 다루다" },
  { eng: "experiment", kor: "[명] 실험 [동] 실험하다" },
  { eng: "patriot", kor: "[명] 애국자" },
  { eng: "interchange", kor: "[동] 교환하다" },
  { eng: "intuitive", kor: "[형] 직감에 의한, 직관력 있는" },
  { eng: "garment", kor: "[명] 의류" },
  { eng: "spontaneous", kor: "[형] 자발적인, 즉흥적인" },
  { eng: "vertical", kor: "[형] 수직의, 세로의 [명] 수직선" },
  { eng: "testify", kor: "[동] 증언하다, 증명하다" },
  { eng: "mentor", kor: "[명] 조언자" },
  { eng: "vivid", kor: "[형] 생생한, 선명한" },
  { eng: "pasture", kor: "[명] 초원" },
  { eng: "crust", kor: "[명] (빵, 파이의)껍질, 딱딱한 표면" },
  { eng: "comprehend", kor: "[동] 이해하다, 파악하다" },
  { eng: "plunge", kor: "[동] 뛰어들다, 급락하다" },
  { eng: "nasty", kor: "[형] 더러운, 비열한" },
  { eng: "appreciate", kor: "[동] 진가를 알아보다, 고맙게 여기다, 감상하다" },
  { eng: "emigrate", kor: "[동] 이민을 가다" },
  { eng: "deed", kor: "[명] 행동, 공적" },
  { eng: "skinny", kor: "[형] 깡마른, 옷이 몸에 딱 붙는" },
  { eng: "grill", kor: "[명] 그릴, 석쇠 [동] 그릴에 굽다" },
  { eng: "canal", kor: "[명] 운하, 수로" },
  { eng: "curse", kor: "[명] 저주" },
  { eng: "adverse", kor: "[형] 불리한, 반대의" },
  { eng: "censorship", kor: "[명] 검열관" },
  { eng: "forehead", kor: "[명] 이마" },
  { eng: "appetite", kor: "[명] 식욕, 욕망" },
  { eng: "flaw", kor: "[명] 결함, 결점" },
  { eng: "outgoing", kor: "[형] 외향적인, 사교적인" },
  { eng: "verbal", kor: "[형] 말의, 구두의" },
  { eng: "liberate", kor: "[동] 해방시키다" },
  { eng: "segregation", kor: "[명] 인종 차별, 차별정책, 분리" },
  { eng: "advance", kor: "[명] 전진하다, 진보하다[명] 발전, 전진, 진보" },
  {
    eng: "contemplate",
    kor: "[동] ~을 숙고하다, 심사숙고하다, 고려하다, 응시하다",
  },
  { eng: "underlying", kor: "[형] 기초를 이루는, 근본적인, 밑에 있는" },
  { eng: "academic", kor: "[형] 학문적인, 학구적인" },
  { eng: "stem", kor: "[명] 줄기[동] 생기다, 일어나다" },
  { eng: " irrigation", kor: "[명] 관개" },
  { eng: "consecutive", kor: "[형] 연이은, 연속적인" },
  { eng: "superficial", kor: "[형] 표면상의, 피상적인" },
  { eng: "refuge", kor: "[명] 피난처, 도피처, 보호구역" },
  { eng: "swear", kor: "[동] 맹세하다, 욕을 하다" },
  { eng: "allergy", kor: "[명] 알레르기" },
  { eng: "norm", kor: "[명] 표준, 규범" },
  { eng: "endeavor", kor: "[동] 노력하다, 시도하다[명] 노력, 시도" },
  { eng: "erect", kor: "[형] 똑바로 선[동] 세우다" },
  { eng: "feminine", kor: "[형] 여성의, 여성스러운" },
  { eng: "drowsy", kor: "[형] 졸리는" },
  { eng: "inspect", kor: "[동] 점검하다, 시찰하다" },
  { eng: "carriage", kor: "[명] 객차, 마차, 운반" },
  { eng: "primitive", kor: "[형] 원시의" },
  { eng: "compress", kor: "[동] 압축하다, 압박하다" },
  { eng: "govern", kor: "[동] 통치하다, 좌우하다" },
  { eng: "cemetery", kor: "[명] 공동묘지" },
  { eng: "shatter", kor: "[동] 산산이 부서지다" },
  { eng: "exaggerate", kor: "[동] 과장하다" },
  { eng: "random", kor: "[형] 무작위의" },
  { eng: "feast", kor: "[명] 잔치, 축제[동] 즐겁게 하다" },
  { eng: "commemorate", kor: "[동] 기념하다" },
  { eng: "steep", kor: "[형] 가파른, 비탈진[동] 몰두시키다, (액체에) 담그다" },
  { eng: "multitask", kor: "[동] 다중작업을 하다" },
  { eng: "toxic", kor: "[형] 유독한, 유독성의" },
  { eng: "stare", kor: "[동] 응시하다" },
  { eng: "chronic", kor: "[형] 만성적인" },
  { eng: "designate", kor: "[동] 지명하다, 지정하다" },
  { eng: "dramatic", kor: "[형] 극적인, 급격한, 감격적인" },
  { eng: "intense", kor: "[형] 강렬한, 극심한, 치열한" },
  { eng: "propaganda", kor: "[명] 선전 활동, 과장된 선전" },
  { eng: "numerous", kor: "[형] 다수의, 많은" },
  { eng: "shiver", kor: "[동] 몸을 떨다떨림" },
  { eng: "retarded", kor: "(정서•지능•학력) 발달이 뒤진" },
  { eng: "ongoing", kor: "[형] 진행 중인진행" },
  { eng: "mention", kor: "[동] 언급하다[명] 언급" },
  { eng: "executive", kor: "[명] 임원[형] 행정의, 관리의" },
  { eng: "chaos", kor: "[명] 혼돈, 혼란" },
  { eng: "microscope", kor: "[명] 현미경" },
  { eng: "belonging", kor: "[명] 소유물, 부속물" },
  { eng: "vulnerable", kor: "[형] 상처받기 쉬운, 취약한" },
  { eng: "implication", kor: "[명] 암시, 영향" },
  { eng: "appetite", kor: "[명] 식욕, 욕망" },
  { eng: "authentic", kor: "[형] 진정한, 진짜의" },
  { eng: "compel", kor: "[동] 강요하다, ~ 하게 만들다" },
  { eng: "transition", kor: "[명] 변화, 전환" },
  { eng: "index", kor: "[명] (책 등의) 색인, 지표" },
  { eng: "incline", kor: "[동] ~쪽으로 기울다, 경사지다, 내키게 하다" },
  { eng: "attain", kor: "[동] 이루다, 달성하다" },
  { eng: "innate", kor: "[형] 타고난" },
  { eng: "ingenuity", kor: "[명] 기발한 재주, 독창성" },
  { eng: "record", kor: "[명] 기록, 증언[동] 기록하다, 녹음하다" },
  { eng: "bias", kor: "[명] 편견, 선입견" },
  { eng: "seize", kor: "[동] 붙잡다, 파악하다" },
  { eng: "screw", kor: "[명] 나사나사로 고정하다" },
  { eng: "savage", kor: "[형] 야만적인, 잔인한[동] 무참히 공격하다야만인" },
  { eng: "province", kor: "[명] 지역, 지방" },
  { eng: "coordinate", kor: "[동] 조직하다, 조정하다[형] 동등한" },
  { eng: "deficient", kor: "부족한, 불완전한" },
  { eng: "privilege", kor: "[명] 특권[동] 특권을 주다" },
  { eng: "preview", kor: "[명] 시사회, 시연, 미리보기" },
  { eng: "equivalent", kor: "[형] 동등한, ~에 상당하는[명] 동등한 것" },
  { eng: "loom", kor: "[동] 어렴풋이 나타나다 베틀" },
  { eng: "purple", kor: "[명] 자주색의" },
  { eng: "outlaw", kor: "[명] 범법자, 도망자금지하다, 법적으로 무효화하다" },
  { eng: "squeeze", kor: "[동] (즙 등을) 짜내다" },
  { eng: "breakthrough", kor: "[명] 돌파구, 비약적 발전" },
  { eng: "consent", kor: "[동] 동의하다, 허락하다[명] 동의, 허락" },
  { eng: "orphan", kor: "[명] 고아" },
  { eng: "negotiate", kor: "[동] 협상하다" },
  { eng: "nuisance", kor: "[명] 골칫거리, 방해, 귀찮은 사람" },
  { eng: "recipe", kor: "[명] 요리법" },
  { eng: "deceive", kor: "[동] 속이다, 기만하다" },
  { eng: "sweep", kor: "[동] 쓸다, 휩쓸다" },
  { eng: "profile", kor: "[명] 옆모습, 윤곽, 인물 소개" },
  { eng: "enterprise", kor: "[명] 기업, 사업" },
  { eng: "successive", kor: "[형] 연속적인" },
  { eng: "paradox", kor: "[명] 역설, 모순되는 말" },
  { eng: "surpass", kor: "[동] 능가하다" },
  { eng: "correlation", kor: "[명] 상관 관계, 연관성" },
  { eng: "magnitude", kor: "[명] 중대성, 거대함" },
  { eng: "aesthetic", kor: "[형] 미의, 미학의" },
  { eng: "earnest", kor: "[형] 성실한, 진심어린" },
  { eng: "tremble", kor: "[동] 떨다, 흔들리다" },
  { eng: "slaughter", kor: "[동] 도살하다, 학살하다" },
  { eng: "surrender", kor: "[동] 항복하다, 양도하다[명] 항복, 양도" },
  { eng: "philosophy", kor: "[명] 철학, 인생관" },
  { eng: "deplete", kor: "[동] 고갈시키다" },
  { eng: "admire", kor: "[동] 존경하다" },
  { eng: "deform", kor: "불구로 만들다, <물리> 변형시키다" },
  { eng: "thrill", kor: "[동] 오싹하다 [명] 오싹함, 떨림" },
  { eng: "afford", kor: "[동] ~할 여유가 있다" },
  { eng: "blunt", kor: "[형] 무뚝뚝한, 직설적인" },
  { eng: "sprint", kor: "[동] 전력 질주하다" },
  { eng: "aid", kor: "[명] 도움, 지원" },
  { eng: "tense", kor: "[형] 긴장한[명] (문법) 시제긴장시키다" },
  { eng: "amplify", kor: "[동] 증폭시키다, 확대하다" },
  { eng: "timber", kor: "[명] 목재" },
  { eng: "collaborate", kor: "[동] 협력하다" },
  { eng: "stance", kor: "[명] 태도, 자세" },
  { eng: "blow", kor: "[동] (입으로) 불다, (바람이) 불다" },
  { eng: "ballot", kor: "[명] 투표투표하다" },
  { eng: "division", kor: "[명] 분할, 분열, 나눗셈" },
  { eng: "acquaintance", kor: "[명] 아는 사람" },
  { eng: "boil", kor: "[동] 끓다, 삶다" },
  { eng: "contradict", kor: "[동] 모순되다, 반박하다, 부정하다" },
  { eng: "burst", kor: "[동] 터지다, 갑자기 나타나다[명] 파열, 폭발" },
  {
    eng: "cast",
    kor: "[동] 던지다, 배역을 정하다, (빛을) 발하다[명] 출연자, 깁스",
  },
  { eng: "falsify", kor: "잘못을 입증하다" },
  { eng: "psychic", kor: "[형] 초자연적인, 마음의" },
  { eng: "paddle", kor: "[명] 노[동] 노를 저어 나아가다" },
  { eng: "steer", kor: "[동] 조종하다" },
  { eng: "affection", kor: "[명] 애착, 애정" },
  { eng: "bid", kor: "말하다" },
  { eng: "compost", kor: "[명] 퇴비, 두엄 [동] 퇴비를 만들다, 두엄을 끼얹다" },
  { eng: "temperament", kor: "[명] 기질" },
  { eng: "rent", kor: "[명] 임대료 [동] 임대하다" },
  { eng: "shred", kor: "[동] 조각조각으로 찢다" },
  { eng: "unpredictable", kor: "[형] 예측할 수 없는" },
  { eng: "tribute", kor: "경의의 표시" },
  { eng: "artery", kor: "[명] 동맥" },
  { eng: "inherent", kor: "[형] 내재하는" },
  { eng: "harass", kor: "[동] 희롱하다" },
  { eng: "narrative", kor: "[형] 서술의, 이야기로 이루어진 [명] 이야기" },
  { eng: "assemble", kor: "[동] 모으다, 조립하다" },
  { eng: "spike", kor: "[명] 못, 뾰족한것" },
  { eng: "sneak", kor: "[동] 몰래 들어가다" },
  { eng: "sophisticated", kor: "[형] 세련된, 정교한" },
  { eng: "handle", kor: "[동] 처리하다, 다루다" },
  { eng: "enlightenment", kor: "깨달음" },
  { eng: "cosmetic", kor: "[명] 화장품 [형] 허울뿐인, 표면적인" },
  { eng: "gracious", kor: "[형] 상냥한" },
  { eng: "aspire", kor: "[동] 열망하다" },
  { eng: "obstruct", kor: "[동] 방해하다, 가로막다" },
  { eng: "patrol", kor: "순찰, 순찰병" },
  { eng: "accelerate", kor: "[동] 가속하다, 촉진하다" },
  { eng: "heatstroke", kor: "일사병" },
  { eng: "oval", kor: "[형] 타원형의 [명] 타원형" },
  { eng: "veteran", kor: "[명] 베테랑, 참전용사" },
  { eng: "trail", kor: "[명] 흔적, 오솔길 [동] 끌다, 추적하다" },
  { eng: "vocation", kor: "[명] 천직, 직업" },
  { eng: "vegetarian", kor: "[명] 채식주의자" },
  { eng: "decode", kor: "해독하다" },
  { eng: "fellow", kor: "[명] 친구, 동료 [형] 동료의" },
  { eng: "mandate", kor: "[명] 권한, 명령 [동] 권한을 부여하다, 명령하다" },
  { eng: "perish", kor: "[동] 소멸하다, 죽다" },
  { eng: "inseparable", kor: "떼어낼 수 없는" },
  { eng: "domain", kor: "[명] 영역, 도메인" },
  { eng: "statesman", kor: "[명] 정치인" },
  { eng: "connotation", kor: "[명] 함축, 내포" },
  { eng: "stereotype", kor: "[명] 인습, 고정관념" },
  { eng: "hollow", kor: "[형] 속이 빈" },
  { eng: "structural", kor: "[형] 구조상의, 구조적인" },
  { eng: "mortgage", kor: "[명] 담보[동] 저당잡히다" },
  { eng: "inject", kor: "[동] 주사하다, 주입하다" },
  { eng: "crisis", kor: "[명] 위기" },
  { eng: "latter", kor: "[형] 나중의, 후자의[명] (둘 중에서) 후자" },
  { eng: "illuminate", kor: "[동] 계몽하다" },
  { eng: "mimic", kor: "[동] 흉내내다" },
  { eng: "unearth", kor: "[동] 발굴하다" },
  { eng: "wail", kor: "[동] 울부짖다, 한탄하다" },
  { eng: "shudder", kor: "[동] (공포, 추위로) 떨다[명] 떨림" },
  { eng: "stride", kor: "[동] 성큼성큼 걷다" },
  { eng: "applicant", kor: "[명] 지원자" },
  { eng: "disprove", kor: "반증하다" },
  { eng: "distrub", kor: "방해하다" },
  { eng: "hemisphere", kor: "[명] (지구, 뇌의) 반구" },
  { eng: "recur", kor: "재발하다" },
  { eng: "elastic", kor: "[형] 탄력있는[명] 고무줄" },
  { eng: "counterpart", kor: "[명] 대응 하는 것" },
  { eng: "stubborn", kor: "[형] 완고한, 고집 센" },
  { eng: "suicide", kor: "[명] 자살" },
  { eng: "lure", kor: "[동] 유혹하다[명] 매력" },
  { eng: "underprivileged", kor: "혜택받지 못한" },
  { eng: "morale", kor: "[명] 사기, 의욕" },
  { eng: "examine", kor: "[동] 조사하다, 검사하다" },
  { eng: "compromise", kor: "[동] 타협하다[명] 타협" },
  { eng: "foremost", kor: "[형] 주요한" },
  { eng: "precaution", kor: "[명] 예방조치, 조심" },
  { eng: "torture", kor: "[명] 고문[동] 고문하다" },
  { eng: "entrust", kor: "[동] 위임하다" },
  { eng: "sway", kor: "[동] 흔들다, 동요시키다" },
  { eng: "religious", kor: "[형] 종교의, 신앙심이 깊은" },
  { eng: "obligation", kor: "[명] 의무, 책임" },
  { eng: "pest", kor: "[명] 해충, 유해동물" },
  { eng: "subdue", kor: "완화하다" },
  { eng: "incorporate", kor: "[동] 통합하다" },
  { eng: "regime", kor: "[명] 정권, 제도" },
  { eng: "terminate", kor: "[동] 끝내다" },
  { eng: "rebel", kor: "반역을 일으키다" },
  { eng: "meanwhile", kor: "[부] 한편" },
  { eng: "folklore", kor: "[명] 민속" },
  { eng: "vast", kor: "[형] 방대한" },
  { eng: "preliminary", kor: "[형] 예비의, 준비의[명] 예비 단계, 예선" },
  { eng: "theft", kor: "[명] 절도" },
  { eng: "painkiller", kor: "진통제" },
  { eng: "amend", kor: "[동] 수정하다" },
  { eng: "recess", kor: "[명] 휴식, 휴업" },
  { eng: "exploit", kor: "[동] 이용하다" },
  { eng: "autonomy", kor: "[명] 자율, 자치" },
  { eng: "outfit", kor: "[명] 복장과 장비" },
  { eng: "mourn", kor: "[동] 애도하다" },
  { eng: "evoke", kor: "[동] 이끌어내다" },
  { eng: "burden", kor: "[명] 부담[동] ~에게 부담을 지우다" },
  { eng: "latitude", kor: "[명] 위도" },
  { eng: "patch", kor: "[명] 조각, 작은 땅[동] 덧대다, 때우다" },
  { eng: "maternal", kor: "[형] 모성의" },
  { eng: "pharmacy", kor: "[명] 약국, 약학" },
  { eng: "marine", kor: "[형] 바다의, 해양의" },
  { eng: "prestigious", kor: "[형] 명성이 있는" },
  { eng: "friction", kor: "[명] 마찰, 충돌" },
  { eng: "defend", kor: "[동] 방어하다" },
  { eng: "fraud", kor: "[명] 사기, 사기꾼" },
  { eng: "easygoing", kor: "태평스러운" },
  { eng: "insomnia", kor: "불면증" },
  { eng: "intermediate", kor: "[형] 중급의, 중간의[명] 중급자" },
  { eng: "transport", kor: "[동] 수송하다[명] 수송" },
  { eng: "paradigm", kor: "[명] 패러다임, 사고체계" },
  { eng: "charge", kor: "[명] 요금, 책임[동] (요금을) 청구하다" },
  { eng: "rapid", kor: "[형] 빠른" },
  { eng: "premature", kor: "[형] 조산한" },
  { eng: "pollute", kor: "[동] 오염시키다" },
  { eng: "altruism", kor: "이타주의" },
  { eng: "fiber", kor: "[명] 섬유질" },
  { eng: "irony", kor: "[명] 아이러니, 비꼼, 반어법" },
  { eng: "spectator", kor: "[명] 관중, 구경꾼" },
  { eng: "medieval", kor: "[형] 중세의" },
  { eng: "analogy", kor: "[명] 유사성" },
  { eng: "snatch", kor: "[동] 잡아채다" },
  { eng: "anthropology", kor: "[명] 인류학" },
  { eng: "outline", kor: "[명] 간략히 기술하다" },
  { eng: "slogan", kor: "[명] 슬로건, 선전 문구" },
  { eng: "composure", kor: "[명] 침착, 평정" },
  { eng: "incurable", kor: "[형] 불치의, 구제 불능의 [명] 불치 환자" },
  { eng: "parallel", kor: "[형] 평행의, 유사한 [명] 평행선 [동] 유사하다" },
  { eng: "indulge", kor: "[동] 탐닉하다.충족시키다" },
  { eng: "meadow", kor: "[명] 목초지, 초원" },
  { eng: "venture", kor: "[동] 모험하다 [명] 모험" },
  { eng: "deflect", kor: "[동] 빗나가다, 빗나가게 하다, 막다" },
  { eng: "adorable", kor: "[형] 귀여운, 사랑스러운" },
  { eng: "complacent", kor: "[형] (스스로) 만족해하는, 현실에 안주하는" },
  { eng: "explicit", kor: "[형] 명백한, 분명한" },
  { eng: "sturdy", kor: "[형] 견고한, 튼튼한" },
  { eng: "primate", kor: "[명] 영장류" },
  { eng: "patron", kor: "[명] 후원자, 단골 손님" },
  { eng: "endure", kor: "[동] 참다, 인내하다, 견디다" },
  { eng: "manifest", kor: "[동] 명백하게 하다, 증명하다 [형] 명백한" },
  { eng: "imperial", kor: "[형] 제국의, 황제의" },
  { eng: "duration", kor: "[명] 지속, 지속 기간" },
  { eng: "populate", kor: "[동] 거주시키다" },
  { eng: "frugal", kor: "[형] 검소한, 절약하는" },
  { eng: "registration", kor: "[명] 기재, 등록" },
  { eng: "rejoice", kor: "[동] 크게 기뻐하다" },
  { eng: "comprise", kor: "[동] 포함하다, 구성하다" },
  { eng: "textile", kor: "[형] 직물의, 방직의 [명] 직물" },
  { eng: "lurk", kor: "[동] 숨다, 잠복하다" },
  { eng: "humanity", kor: "[명] 인류, 인간성, 인간애" },
  { eng: "approximate", kor: "[동] (수량 등이) ~에 가까워지다 [형] 대략의" },
  { eng: "revenge", kor: "[명] 복수 [동] 복수하다" },
  { eng: "sarcastic", kor: "[형] 비꼬는, 풍자적인" },
  { eng: "terrain", kor: "[명] 지형, 지역, 분야, 범위" },
  { eng: "toll", kor: "[명] 사용세, 통행료, 종소리 [동] 요금으로 징수하다" },
  { eng: "warfare", kor: "[명] 전쟁, 전투, 교전 상태" },
  { eng: "mortal", kor: "[형] 죽을 운명의, 치명적인 [명] 인간" },
  { eng: "spouse", kor: "[명] 배우자" },
  { eng: "crispy", kor: "[형] 바삭바삭한, 부서지기 쉬운" },
  { eng: "statistical", kor: "[형] 통계적인, 통계상의" },
  { eng: "rubbish", kor: "[명] 쓰레기, 폐기물 [동] 혹평하다" },
  { eng: "stimulus", kor: "[명] 자극, 격려" },
  { eng: "clumsy", kor: "[형] 서투른, 어색한" },
  { eng: "subsequent", kor: "[형] 다음의, 그 이후의" },
  { eng: "relevant", kor: "[형] 관련된, 적절한" },
  { eng: "predator", kor: "[명] 포식자, 약탈자, 육식 동물" },
  { eng: "drain", kor: "[동] 물을 빼내다, 소모시키다 [명] 배수관" },
  { eng: "countless", kor: "[형] 셀 수 없는, 무수한" },
  { eng: "condense", kor: "[동] 농축하다, 요약하다" },
  { eng: "post", kor: "[동] (벽 따위에) 붙이다, 우편" },
  { eng: "poise", kor: "[동] 균형을 잡다 [명] 균형, 평정" },
  { eng: "disciple", kor: "[명] 제자, 문하생" },
  { eng: "gust", kor: "[명] 돌풍, 질풍" },
  { eng: "collective", kor: "[형] 집합적인, 집단적인 [명] 집단" },
  { eng: "scope", kor: "[명] (관찰, 활동의) 범위, 시야 [동] 조사하다" },
  { eng: "compatible", kor: "[형] 양립할 수 있는, 모순이 없는" },
  { eng: "border", kor: "[명] 경계, 가장자리, 국경 [동] 인접하다" },
  { eng: "frontier", kor: "[명] 국경 [형] 국경의, 최첨단의" },
  { eng: "withhold", kor: "[동] 억누르다, 억제하다, 보류하다" },
  { eng: "verdict", kor: "[명] 판결, 결정" },
  { eng: "stall", kor: "[명] 마구간, 우리 [동] 핑계를 대다" },
  { eng: "apparatus", kor: "[명] 장치, 기구, 조직" },
  { eng: "hail", kor: "[명] 우박, 싸락눈 [동] 우박이 내리다" },
  { eng: "outburst", kor: "[명] 폭발, 분출" },
  { eng: "vanity", kor: "[명] 허영심, 허무함" },
  { eng: "firsthand", kor: "[형] 직접의 [부] 직접, 바로" },
  { eng: "obesity", kor: "[명] 비만, 비대" },
  { eng: "dilemma", kor: "[명] 진퇴양난, 딜레마, 궁지" },
  { eng: "render", kor: "[동] ~이 되게 하다, 주다, 제공하다" },
  { eng: "indispensable", kor: "[형] 필수 불가결한 [명] 없어서는 안 될 것" },
  { eng: "outdated", kor: "[형] 구식의, 시대에 뒤진" },
  { eng: "bother", kor: "[동] 일부러~ 하다, 괴롭히다" },
  { eng: "counteract", kor: "[동] (효력을) 중화시키다, 약화시키다" },
  { eng: "static", kor: "[형] 정적인, 고정된" },
  { eng: "sustain", kor: "[동] 유지하다, 지탱하다" },
  { eng: "posture", kor: "[명] 자세, 태도" },
  { eng: "discourse", kor: "[명] 담화, 강연" },
  { eng: "bribe", kor: "[명] 뇌물 [동] 뇌물을 주다" },
  { eng: "retention", kor: "[명] 보유, 기억력" },
  { eng: "valiant", kor: "[형] 용감한, 용맹스런" },
  { eng: "distress", kor: "[명] 고민, 고통 [동] ~을 괴롭히다" },
  { eng: "nursery", kor: "[명] 육아실, 탁아소" },
  { eng: "juggle", kor: "[동] 잘 처리하다, 저글링하다" },
  { eng: "perspiration", kor: "[명] 땀, 노력" },
  { eng: "encircle", kor: "[동] 에워싸다, 둘러싸다" },
  { eng: "notion", kor: "[명] 개념, 의견" },
  { eng: "disgust", kor: "[명] 혐오감 [동] 역겹게 하다" },
  { eng: "fragment", kor: "[명] 일부분, 부서진 조각 [동] 산산이 부서지다" },
  { eng: "oversee", kor: "[동] 감독하다, 감시하다" },
  { eng: "creep", kor: "[동] 기다, (덩굴 등이) 얽히다 [명] 포복, 서행" },
  { eng: "clarify", kor: "[동] 명백히 하다" },
  { eng: "contagious", kor: "[형] 전염성의, 감염성의" },
  { eng: "deterioration", kor: "[명] 악화, (가치의) 하락, 저하" },
  { eng: "currency", kor: "[명] 통화, 통용" },
  { eng: "janitor", kor: "[명] 문지기, 관리인, (건물) 경비원" },
  { eng: "blush", kor: "[동] 얼굴을 붉히다, 부끄러워 하다" },
  { eng: "intervene", kor: "[동] 끼어들다, 개입하다, 방해하다" },
  { eng: "nomad", kor: "[명] 유목민, 방랑자" },
  { eng: "cuisine", kor: "[명] 요리, 요리법" },
  { eng: "dare", kor: "[동] 감히 ~하다" },
  {
    eng: "solvent",
    kor: "[형] 용해력이 있는, 지불 능력이 있는 [명] 용제, 용액",
  },
  { eng: "cultivate", kor: "[동] 경작하다, 양성하다, 계발하다" },
  { eng: "ascent", kor: "[명] 상승, 오름" },
  { eng: "advocate", kor: "[명] 옹호자, 지지자 [동] 지지하다" },
  {
    eng: "spur",
    kor: "[명] 자극, 고무 [동] ~을 자극하다, (말에) 박차를 가하다",
  },
  { eng: "discern", kor: "[동] 식별하다, 분별하다, ~을 인식하다" },
  { eng: "scheme", kor: "[명] 계획, 체계 [동] 계획하다" },
  { eng: "weigh", kor: "[동]  무게를 달다" },
  { eng: "publicity", kor: "[명] 널리 알려짐, 명성, 광고, 선전" },
  { eng: "declare", kor: "[동] 선언하다, (세관에) 신고하다" },
  { eng: "brisk", kor: "[형] 활발한, 번창하는, 상쾌한" },
  { eng: "exile", kor: "[명] 망명, 망명자 [동] 망명시키다" },
  { eng: "whisper", kor: "[동] 속삭이다 [명] 속삭임" },
  { eng: "fling", kor: "[동] 내던지다, 돌진하다" },
  { eng: "deviation", kor: "[명] 변경, 일탈" },
  { eng: "dissolve", kor: "[동] 용해하다, 해산하다, 해소하다" },
  { eng: "constraint", kor: "[명] 강제, 압박, 제약" },
  { eng: "itch", kor: "[동] 가려움, 가렵다, (~하고 싶어) 못 견디다" },
  { eng: "unanimous", kor: "[형] 만장일치의, 합의의" },
  { eng: "delude", kor: "[동] 속이다, 착각하게 하다" },
  { eng: "dehydrate", kor: "[동] 탈수하다, 건조시키다" },
  { eng: "underneath", kor: "[전] ~의 아래에, 밑에" },
  { eng: "metabolism", kor: "[명] 물질대사, 신진대사" },
  { eng: "appoint", kor: "[동] 임명[지명]하다, (시간, 장소를) 정하다" },
  { eng: "pinch", kor: "[동] 꼬집다, 집다, 죄다" },
  { eng: "punctual", kor: "[형] 시간을 지키는" },
  { eng: "arbitrary", kor: "[형] 임의적인, 독단적인" },
  { eng: "catastrophe", kor: "[명] 대참사, 재앙" },
  { eng: "exert", kor: "[동] (힘, 영향력을) 가하다, 발휘하다" },
  { eng: "aviate", kor: "[동] 조종하다, 비행하다" },
  { eng: "headquarters", kor: "[명] 본사, 본부" },
  { eng: "rectangular", kor: "[형] 직사각형의, 직각의" },
  { eng: "deledate", kor: "[동] 파견하다 [명] 사절, 대표" },
  { eng: "elect", kor: "[동] 선출하다" },
  { eng: "thorn", kor: "[명] 가시" },
  { eng: "empathize", kor: "[동] 공감하다" },
  { eng: "expertise", kor: "[명] 전문 지식" },
  { eng: "renovate", kor: "[동] ~을 새것으로 만들다, 수리하다" },
  { eng: "wrench", kor: "[동] 비틀다, 삐다  [명] 렌치, 쓰라림" },
  { eng: "interval", kor: "[명] 간격, 사이" },
  { eng: "degrade", kor: "[동] 저하시키다, 비하하다, 분해하다" },
  { eng: "report", kor: "[명] 보고서, 말대꾸 [동] 보고하다, 발표하다" },
  { eng: "asthma", kor: "[명] 천식" },
  { eng: "realm", kor: "[명] 영역, 왕국" },
  { eng: "segment", kor: "[명] 부분, 조각" },
  { eng: "coexist", kor: "[동] 공존하다" },
  { eng: "hospitality", kor: "[명] 환대, 후한 대접" },
  { eng: "estate", kor: "[명] 재산, 토지" },
  { eng: "displace", kor: "[동] 옮겨 놓다, 대체하다" },
  {
    eng: "cripple",
    kor: "[명] 불구자, 지체 부자유자 [동] ~을 불구로 만들다, 손상시키다",
  },
  { eng: "drawback", kor: "[명] 문제점, 결점, 장애" },
  { eng: "tactics", kor: "[명] 방안, 전술" },
  { eng: "dread", kor: "[동] 두려워하다, 무서워하다 [명] 두려움, 공포" },
  { eng: "dispute", kor: "[동] 논쟁하다, 토의하다 [명] 논쟁, 분쟁" },
  { eng: "console", kor: "[동] 위로하다" },
  { eng: "stack", kor: "[명] 더미, 산더미 [동] 쌓아 올리다" },
  { eng: "cynical", kor: "[형] 냉소적인, 비관적인" },
  { eng: "reprove", kor: "[동] 꾸짖다, 책망하다" },
  { eng: "verify", kor: "[동] 입증하다" },
  { eng: "engross", kor: "[동] 열중하게 하다" },
  {
    eng: "bulk",
    kor: "[명] 크기, 부피, 대부분 [동] 부피가 커지다, 덩어리가 되다",
  },
  { eng: "despise", kor: "[동] 경멸하다" },
  { eng: "manuscript", kor: "[명] 원고, 필사본" },
  { eng: "flee", kor: "[동] 달아나다" },
  { eng: "prehistoric", kor: "[형] 선사시대의" },
  { eng: "barrel", kor: "[명] 통, 배럴" },
  { eng: "predecessor", kor: "[명] 이전 형태, 전임자" },
  { eng: "alienate", kor: "[동] 소외시키다, 멀리하다" },
  { eng: "preclaim", kor: "[동] 선언하다, 선포하다" },
  {
    eng: "subordinate",
    kor: "[형] 하위의, 부차적인[명] 하급자[동] 하위에 두다",
  },
  { eng: "furnish", kor: "[동] (가구를) 비치하다, 제공하다, 갖추다" },
  { eng: "fume", kor: "[동] 씩씩대다, 연기를 내뿜다[명] 연기" },
  { eng: "staple", kor: "[형] 주된, 주요한[명] 주성분" },
  { eng: "dimension", kor: "[명] 크기, 측면, 치수, 차원" },
  { eng: "dispersal", kor: "[명] 분산, 확산" },
  {
    eng: "eloquent",
    kor: "[형] 웅변의, 달변의, 연설을 잘 하는, 표현이 풍부한",
  },
  { eng: "innermost", kor: "[형] 가장 깊숙한[명] 가장 깊은 부분" },
  { eng: "hazardous", kor: "[형] 위험한, 해로운" },
  { eng: "skull", kor: "[명] 두개골" },
  { eng: "detergent", kor: "[명] 세제" },
  { eng: "brutal", kor: "[형] 야만적인, 잔혹한" },
  { eng: "rash", kor: "[명] 반점, 발진[형] 경솔한" },
  { eng: "bypass", kor: "[명] 우회로[동] 우회하다" },
  { eng: "accommodate", kor: "[동] 수용하다, 적응하다" },
  { eng: "tact", kor: "[명] 재치, 기지" },
  { eng: "monotonous", kor: "[형] 단조로운, 지루한" },
  { eng: "perpetual", kor: "[형] 영원한, 끊임없는" },
  { eng: "eligible", kor: "[형] ~을 할 수 있는, 유능한, 자격의, 자격이 있는" },
  { eng: "legacy", kor: "[명] 유물, 유산" },
  { eng: "melancholy", kor: "[형] 우울한[명] 우울함" },
  { eng: "simplicity", kor: "[명] 단순함, 간단" },
  { eng: "hierarchy", kor: "[명] 계층, 계급, 지배층, 체계" },
  { eng: "reside", kor: "[동] 거주하다" },
  { eng: "enact", kor: "[동] 제정하다, 상영하다" },
  { eng: "burnout", kor: "[명] 극도의 피로, 쇠진" },
  { eng: "legitimate", kor: "[형] 타당한, 합법적인, 정당한" },
  { eng: "shuffle", kor: "[동] 발을 끌며 걷다, 뒤섞다" },
  { eng: "summarize", kor: "[동] 요약하다" },
  { eng: "eject", kor: "[동] 쫓아내다, 튀어나오게 하다" },
  { eng: "intersection", kor: "[명] 교차로, 교차함" },
  { eng: "quest", kor: "[명] 탐색, 탐구, 추구, 찾음" },
  { eng: "linear", kor: "[형] 직선의, 길이의" },
  { eng: "landslide", kor: "[명] 산사태, (선거에서) 압도적 승리" },
  { eng: "plausible", kor: "[형] 그럴듯한, 이치에 맞는" },
  { eng: "endow", kor: "[동] 기부하다, ~에게 부여하다" },
  { eng: "extrinsic", kor: "[형] 외적인, 외부의" },
  { eng: "merge", kor: "[동] 합병하다, 차차 변하다" },
  { eng: "frantic", kor: "[형] 광란의, 미친" },
  { eng: "moan", kor: "[명] 신음, 투덜거림 [동] 신음하다, 불평하다" },
  { eng: "merchandise", kor: "[명] (집학적) 상품 [동] 거래하다" },
  { eng: "respectively", kor: "[부] 각각, 저마다" },
  { eng: "yearn", kor: "[동] 그리워하다, 열망하다" },
  { eng: "conviction", kor: "[명] 확신, 유죄 판결" },
  { eng: "stout", kor: "[형] 뚱뚱한, (옷 등이) 튼튼한" },
  { eng: "reckon", kor: "[동] 세다, 계산하다, 생각하다" },
  { eng: "enchant", kor: "[동] 매혹하다, ~에게 마법을 걸다" },
  { eng: "entail", kor: "[동] 수반하다, 의미하다, 필요로 하다" },
  { eng: "demolish", kor: "[동] 파괴하다, 폐지하다" },
  { eng: "degenerate", kor: "[동] 퇴보하다, 타락하다" },
  { eng: "sentiment", kor: "[명] 감상, 정서" },
  { eng: "offspring", kor: "[명] 자식, 새끼, 성과" },
  { eng: "detest", kor: "[동] 혐오하다, 미워하다" },
  {
    eng: "tackle",
    kor: "[동] (일, 문제를) 다루다, 처리하다 [명] 도구, (축구의) 태클",
  },
  { eng: "defy", kor: "[동] 물리치다, (공공연히) 무시하다, 반항하다" },
  { eng: "inference", kor: "[명] 추론" },
  { eng: "refraction", kor: "[명] (빛, 소리 따위의) 굴절" },
  { eng: "dusk", kor: "[명] 땅거미, 어스름" },
  { eng: "detach", kor: "[동] 떼어내다, 분리하다" },
  { eng: "antagonist", kor: "[명] 적대자, 라이벌" },
  { eng: "thrust", kor: "[동] 밀다, 밀치다, 찌르다" },
  { eng: "creed", kor: "[명] 신념, (종교의) 교의" },
  { eng: "equate", kor: "[동] 동일시하다, 일치하다" },
  { eng: "misplace", kor: "[동] 잘못두다" },
  { eng: "auditory", kor: "[형] 귀의, 청각의, 음향의" },
  { eng: "missionary", kor: "[명] 선교사" },
  { eng: "cosmopolitan", kor: "[형] 세계적인, 세계주의의 [명] 세계인, 국제인" },
  { eng: "secondhand", kor: "[형] 중고의, 간접적인" },
  { eng: "multiple", kor: "[형] 복합적인, 다수의, 다양한 [명] (수학) 배수" },
  { eng: "embed", kor: "[동] 깊숙이 박다, 깊이 간직하다, 내재하다" },
  { eng: "propel", kor: "[동] 나아가게 하다, 추진하다" },
  { eng: "reptile", kor: "[명] 파충류" },
  { eng: "erosion", kor: "[명] 부식, 침식" },
  { eng: "feat", kor: "[명] 위업, 공적, 솜씨" },
  { eng: "utensil", kor: "[명] 가정용품, 기구, 도구" },
  { eng: "penetrate", kor: "[동] 관통하다, 꿰뚫다, 침투하다" },
  { eng: "intrude", kor: "[동] 침범하다, 방해하다" },
  { eng: "notable", kor: "[형] 주목할 만한, 유명한" },
  { eng: "grumble", kor: "[동] 불평하다, 투덜거리다 [명] 불평" },
  { eng: "landfill", kor: "[명] 쓰레기 매립지" },
  { eng: "scrutiny", kor: "[명] (정밀) 조사, 철저한 검토" },
  { eng: "reckless", kor: "[형] 무모한, 부주의한, 신중하지 못한" },
  { eng: "synthetic", kor: "[형] 합성의, 종합적인" },
  { eng: "productive", kor: "[형] 생산하는, 생산적인" },
  { eng: "outset", kor: "[명] 착수, 발단, 시작, 처음" },
  { eng: "peril", kor: "[명] 위험" },
  { eng: "pitfall", kor: "[명] 위험, 함정" },
  { eng: "kidnap", kor: "[동] 납치하다 [명] 유괴" },
  { eng: "liable", kor: "[형] 책임이 있는, ~하기 쉬운" },
  { eng: "insane", kor: "[형] 정신 이상의, 미친, 비상식적인" },
  { eng: "rage", kor: "[명] 격노 [동] 격노하다" },
  { eng: "radius", kor: "[명] 반지름" },
  { eng: "hybrid", kor: "[명] 잡종, 혼합물" },
  { eng: "uncover", kor: "[동] 폭로하다, 덮개를 벗기다" },
  { eng: "limb", kor: "[명] 사지, 팔다리, 나뭇가지" },
  { eng: "setback", kor: "[명] 좌절, 차질, 방해, 실패" },
  { eng: "prudent", kor: "[형] 신중한" },
  { eng: "solidify", kor: "[동] 굳어지다, 굳히다, 확고히 하다" },
  { eng: "grudge", kor: "[명] 원한, 유감" },
  { eng: "lessen", kor: "[동] 줄이다" },
  { eng: "tangle", kor: "[동] 얽히게 하다, 혼란시키다" },
  { eng: "subsidy", kor: "[명] 보조금, 장려금" },
  { eng: "ambiguous", kor: "[형] 애매모호한, 불명확한" },
  { eng: "enthusiasm", kor: "[명] 열광, 열정, 열광하는 대상" },
  { eng: "bankruptcy", kor: "[명] 파산" },
  { eng: "pollination", kor: "[명] 수분" },
  { eng: "prosper", kor: "[동] 번영하다, 번창하다" },
  { eng: "phase", kor: "[명] 단계" },
  { eng: "veterinarian", kor: "[명] 수의사" },
  { eng: "counterattack", kor: "[명] 반격, 연습 [동] 반격하다, 역습하다" },
  { eng: "cumulative", kor: "[형] 누적되는" },
  { eng: "infrastructure", kor: "[명] (사회) 기반 시설, 하부 조직" },
  { eng: "wound", kor: "[동] 상처를 입히다, 부상하게 하다 [명] 부상, 상처" },
  { eng: "discrete", kor: "[형] 별개의" },
  { eng: "fluctuation", kor: "[명] 변동, 동요" },
];
